$axure.loadCurrentPage({
  "url":"权限请求.html",
  "generationDate":new Date(1497322447131.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cd202cd9eb0c414b9e8bb0fa844d7c6d",
    "type":"Axure:Page",
    "name":"权限请求",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFD7D7D7},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"76ce45d76eba45c293a7df57f31a3de3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":300,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05dbaf0bd2cb4953abc634f4fb0d5fdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":300,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/权限请求/u0.png"}},
{
          "id":"0a7d680cc7564bd39bd0ee16eac3cb95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":59,
              "y":20},
            "size":{
              "width":193,
              "height":19},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ba26f1e7e2f469497ef8c88097dc63e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":59,
                  "y":20},
                "size":{
                  "width":193,
                  "height":19},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"991df3d3fdd1451d8aced3169a5bc789",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":52},
            "size":{
              "width":248,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b015a1a3504440109552d06f28c76bcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":52},
                "size":{
                  "width":248,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d298b14c272749b8a4f4f7293d74e4c7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":100},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u6_line.png"}},
{
          "id":"4e01a222b6bd4ad588a338a7f8b83439",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":105},
            "size":{
              "width":10,
              "height":45}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u7_line.png"}},
{
          "id":"7a577ba0324844de8ae3ff99717ea2ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":44,
              "y":120},
            "size":{
              "width":46,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef71d71c3b1b440abeace360dce742a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":120},
                "size":{
                  "width":46,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"378028515296403ea5a6b5a9a95f4612",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":200,
              "y":120},
            "size":{
              "width":31,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80d6c4e6a9d1498e9666f92de7d8584b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":120},
                "size":{
                  "width":31,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eccb4ed251c34d9ca9fd16bdaeb07fad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":0},
            "size":{
              "width":300,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"921fc1de3eff44bc908aa0baae839746",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":0},
                "size":{
                  "width":300,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/权限请求/u0.png"}},
{
          "id":"d610c665b54241268c1e6a79c31f605b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":400,
              "y":20},
            "size":{
              "width":209,
              "height":19},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee286d647f03492c80c508b7c1b1ff16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":400,
                  "y":20},
                "size":{
                  "width":209,
                  "height":19},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"287731c279f746938cf18aac48481c01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":383,
              "y":52},
            "size":{
              "width":260,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70d13ca0426445a8af5552af97cfdad8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":383,
                  "y":52},
                "size":{
                  "width":260,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23991922d5c24a9d823815ef8651849d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":100},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u6_line.png"}},
{
          "id":"bc0027e6bbfd41259f467211952d56b9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":105},
            "size":{
              "width":10,
              "height":45}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u7_line.png"}},
{
          "id":"f61cd3b5b3d54d6fa55d074c349c46d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":419,
              "y":120},
            "size":{
              "width":31,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b703881e160c4b6fbf6975d7fa812b5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":419,
                  "y":120},
                "size":{
                  "width":31,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be6a2648bce545d18ba7b299b8f98b17",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":560,
              "y":120},
            "size":{
              "width":16,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b378058fdfc4bc9a3c0932ba2bdd6ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":560,
                  "y":120},
                "size":{
                  "width":16,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b39fe13cde64a919e48f735970606fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":220},
            "size":{
              "width":300,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55e7c44975b14ccd852556152e05a341",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":220},
                "size":{
                  "width":300,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/权限请求/u0.png"}},
{
          "id":"c42bdfc0f0254d1cb4d59b10ef73d42b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":59,
              "y":240},
            "size":{
              "width":193,
              "height":19},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0e4043c56844c9d8306a87ef7117e07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":59,
                  "y":240},
                "size":{
                  "width":193,
                  "height":19},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00a78dcb3aa14da8af36fe5da7620c11",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":272},
            "size":{
              "width":248,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"808cc2b0c4c1476580a3111c19240a2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":272},
                "size":{
                  "width":248,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17f17e00c7224cf89a4fdad994df82ce",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":320},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u6_line.png"}},
{
          "id":"4efcfee4aad84e64a168231eeda683c1",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":325},
            "size":{
              "width":10,
              "height":45}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u7_line.png"}},
{
          "id":"78714c60afd1494291a04eab128658cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":44,
              "y":340},
            "size":{
              "width":46,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08e24ac2b2db49c486124add92004211",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":340},
                "size":{
                  "width":46,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36ff1d2bca9d48b3b9f4025d566e72f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":200,
              "y":340},
            "size":{
              "width":31,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06b4c77f2fec44fcb25d433dfe88aabc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":340},
                "size":{
                  "width":31,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"deed9300e1414cada534422dc7ebb5fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":440},
            "size":{
              "width":300,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc3c4293c8474c3aa27fc226d57415a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":440},
                "size":{
                  "width":300,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/权限请求/u0.png"}},
{
          "id":"7fdff4249e394d2190911e7cdec6746a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":59,
              "y":460},
            "size":{
              "width":193,
              "height":19},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a672daa021bb40238e963822227aa343",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":59,
                  "y":460},
                "size":{
                  "width":193,
                  "height":19},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"affee51f3e0743ebbd457cb605c219c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":492},
            "size":{
              "width":248,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92703f2178444e618728c58e18cbeb72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":492},
                "size":{
                  "width":248,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e53e164893224100bafb8014a2e7c09f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":540},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u6_line.png"}},
{
          "id":"2a4060585a8e42208aad3e5f4fe104f0",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":545},
            "size":{
              "width":10,
              "height":45}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u7_line.png"}},
{
          "id":"08b30d778d4146458b17269b35af081b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":44,
              "y":560},
            "size":{
              "width":46,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"754a981b38284ad7873fe3dc0ad34027",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":560},
                "size":{
                  "width":46,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a2eaa2bc1fe42b9bd997982bede33cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":200,
              "y":560},
            "size":{
              "width":31,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daa7e0de26f5464dbacb5217579023fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":560},
                "size":{
                  "width":31,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0261ec6d86ac4004ab5c9696c59d9eb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":640},
            "size":{
              "width":300,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d319782261be489190b490096856384e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":640},
                "size":{
                  "width":300,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/权限请求/u0.png"}},
{
          "id":"77d72ec1c3a349a9ad6d480d1781655b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":59,
              "y":660},
            "size":{
              "width":209,
              "height":19},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c06e4d17c00c4833b9792ebd6db2f410",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":59,
                  "y":660},
                "size":{
                  "width":209,
                  "height":19},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a409df8270b44c68834c5e67261ad47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":692},
            "size":{
              "width":248,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82402d2ddb4f4fa68192845958474246",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":692},
                "size":{
                  "width":248,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c5e7e33a49149ad8e5f6b9531c2bab9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":740},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u6_line.png"}},
{
          "id":"a0629dc0a2354ab59596c9426d473175",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":745},
            "size":{
              "width":10,
              "height":45}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u7_line.png"}},
{
          "id":"781417202127433d91c90039a0c79d99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":44,
              "y":760},
            "size":{
              "width":46,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"345949d099bb45e693906837d9ab773a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":760},
                "size":{
                  "width":46,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e0b64b7067b4e59b665aaed1cd13e9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":200,
              "y":760},
            "size":{
              "width":31,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94de85dc16a0492aa3a2cefc956ee579",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":760},
                "size":{
                  "width":31,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b5a93a7c245477da6fe09ee965c63f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":160},
            "size":{
              "width":158,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa5cd4c6667344ab85d4400ff6f988bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":160},
                "size":{
                  "width":158,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"209f2afae7d54dfda4695eb4a7ff5ad5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":600},
            "size":{
              "width":301,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d1cd12ae8ff4101a14607a19bfddf6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":600},
                "size":{
                  "width":301,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c5e36a6eb854df19d4693ba2cc50794",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":804},
            "size":{
              "width":301,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78f6849e84ed49c689c7d0cdcadccef7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":804},
                "size":{
                  "width":301,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cdc44f923694b649c13188b40b5512e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":390},
            "size":{
              "width":158,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58bb62d8a037428aab9feea37ef6835f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":390},
                "size":{
                  "width":158,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4d02876922a428c995bd495c87acbe0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":220},
            "size":{
              "width":300,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"011e4a5ba16848858a355c7cdedf7fce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":220},
                "size":{
                  "width":300,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/权限请求/u0.png"}},
{
          "id":"eee013474e164fb8a1037856f495ae88",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":464,
              "y":240},
            "size":{
              "width":81,
              "height":19},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0865de68082b4dd8a79009c1583379b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":464,
                  "y":240},
                "size":{
                  "width":81,
                  "height":19},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d99cfe79ce041438eebe7c2545f84e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":272},
            "size":{
              "width":260,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b677ba267614523a4166838ff2c2286",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":272},
                "size":{
                  "width":260,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b5e216602e647dd85d5b80443f2957a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":320},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u6_line.png"}},
{
          "id":"b162ff98717c497a9ef1e2dd3342ba35",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":325},
            "size":{
              "width":10,
              "height":45}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u7_line.png"}},
{
          "id":"1f78bccb075740b3858f9079d3836971",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":419,
              "y":340},
            "size":{
              "width":31,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9b3863c62a9460c82a4d4ddc0accc61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":419,
                  "y":340},
                "size":{
                  "width":31,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f0ea47789f7445ea5ac6cbc8f315dd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":560,
              "y":340},
            "size":{
              "width":16,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe82fbbb26814c129e25a7a17f3def2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":560,
                  "y":340},
                "size":{
                  "width":16,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7adbb4e42bfe46f5997b5410e1ffb9cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":440},
            "size":{
              "width":300,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cc9360ed9284d2ca2a3a307bd8ad9e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":440},
                "size":{
                  "width":300,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/权限请求/u0.png"}},
{
          "id":"a8b19ad5e5af4d23bcc88faca6ef7370",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":464,
              "y":457},
            "size":{
              "width":81,
              "height":19},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e13cd3edcc394881b7efd6fa1dd960dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":464,
                  "y":457},
                "size":{
                  "width":81,
                  "height":19},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97889e67f8c746e086ae13ac0d3d28e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":487},
            "size":{
              "width":260,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ffbf011dc2448b8831491a39041ec80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":487},
                "size":{
                  "width":260,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d86173fbb7b147c399db749da8d92cd3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":540},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u6_line.png"}},
{
          "id":"4dc9f7b401e04640ac943787671dfe4b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":545},
            "size":{
              "width":10,
              "height":45}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u7_line.png"}},
{
          "id":"3a54e47753ba4d1dae85979dd448217c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":419,
              "y":560},
            "size":{
              "width":31,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e71fc08ef29a4c8f8641153b23bfb9ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":419,
                  "y":560},
                "size":{
                  "width":31,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa46eec356b84786a9d6da1a08b619b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":560,
              "y":560},
            "size":{
              "width":16,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ef766213d6e42ee8faa03267f5f61ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":560,
                  "y":560},
                "size":{
                  "width":16,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da105fefaf164d9ea8c9a42dfc1f4747",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":160},
            "size":{
              "width":183,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cd8c6da91f741059975346972be2271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":160},
                "size":{
                  "width":183,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57254ff7033f4571a87a7401f30dd62d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":600},
            "size":{
              "width":261,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"499884b4b01d481880d6dc0d0b79ffad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":600},
                "size":{
                  "width":261,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68c25f815e7f4eeb962f093064b3d743",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":860},
            "size":{
              "width":300,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"967fe0161e6249a99a83446370b93282",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":860},
                "size":{
                  "width":300,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/权限请求/u0.png"}},
{
          "id":"cd2cdfc280ef4615b74b5732eccc45dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":18,
              "y":880},
            "size":{
              "width":273,
              "height":38},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c534f6a1084d42fda1bddc65ea33d1fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":18,
                  "y":880},
                "size":{
                  "width":273,
                  "height":38},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62cefb68252f4d1f9509d3bdcb561ebb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":934},
            "size":{
              "width":248,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dc1fbcf0d294a59991151f0410fde42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":37,
                  "y":934},
                "size":{
                  "width":248,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45a8ff54ea0744eea2a3d3d81404c26b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":960},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u6_line.png"}},
{
          "id":"7f0f47a790e04183b2b88aad182c9ae7",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":965},
            "size":{
              "width":10,
              "height":45}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u7_line.png"}},
{
          "id":"0d1c054b2b4c4439920d47d0a7180b86",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":44,
              "y":980},
            "size":{
              "width":46,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc86b01829d14fbda4b2ac49625ace02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":980},
                "size":{
                  "width":46,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5aafb758d7e402eb0d7dd312d0f408e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":200,
              "y":980},
            "size":{
              "width":31,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a833e42748141f6912488c6aed06e87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":980},
                "size":{
                  "width":31,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"014a7d1e4b254a0185532b13d4994d0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1020},
            "size":{
              "width":236,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7202b065ad784facb0fd463be99df706",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1020},
                "size":{
                  "width":236,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da4bdd8c611d417595ef7011a62bf893",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":640},
            "size":{
              "width":300,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70b41457bc8844878c658b096b878d19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":640},
                "size":{
                  "width":300,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/权限请求/u0.png"}},
{
          "id":"c9330a8610b64500bf65498310ab6a3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":456,
              "y":657},
            "size":{
              "width":97,
              "height":19},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7adaf6eaa2e84fcdad8892ec9743e1a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":456,
                  "y":657},
                "size":{
                  "width":97,
                  "height":19},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a8c9769b5154b8c8219763bca2b9d9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":687},
            "size":{
              "width":260,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"477e88052b644543aafe27adb894cea1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":687},
                "size":{
                  "width":260,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee8e416ddb474faaab3926fd6789b59a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":740},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u6_line.png"}},
{
          "id":"f944c126cb0642a0b0af3ae24f6f8f2b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":745},
            "size":{
              "width":10,
              "height":45}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u7_line.png"}},
{
          "id":"f9c358c86a0c41a6b43f9a95584ad30e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":419,
              "y":760},
            "size":{
              "width":31,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a983458c40343b9b4aee26d11450742",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":419,
                  "y":760},
                "size":{
                  "width":31,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2ab2825dddd4cf2a6bbc107f754a233",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":560,
              "y":760},
            "size":{
              "width":16,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"350d5e2c71f14f70b2526b42c742f37f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":560,
                  "y":760},
                "size":{
                  "width":16,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"509aa448090c422eaaf960b0ce1e37d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":800},
            "size":{
              "width":300,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"704247ecd9dc495084fc671bbb2dc854",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":800},
                "size":{
                  "width":300,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01845ae16c4b4a0782ed058ff1ee4daf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":860},
            "size":{
              "width":300,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8bd3957e89e490b8b050ab6b0106b64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":860},
                "size":{
                  "width":300,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/权限请求/u0.png"}},
{
          "id":"84f8508553674621a358e1bcdc4d7004",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":464,
              "y":877},
            "size":{
              "width":81,
              "height":19},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb0001e9c33046a09eec667383441904",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":464,
                  "y":877},
                "size":{
                  "width":81,
                  "height":19},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25213b69fa3b4024ae8dc2597608bd9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":907},
            "size":{
              "width":260,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1488d768b1a24074b43b6527479612ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":379,
                  "y":907},
                "size":{
                  "width":260,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17ccfa1ce43a40879363b5b89983d0f7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":960},
            "size":{
              "width":300,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u6_line.png"}},
{
          "id":"0ff1f7345e494ed1a7d9fa1ab3c06140",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":965},
            "size":{
              "width":10,
              "height":45}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/权限请求/u7_line.png"}},
{
          "id":"8c71d8b43e31403a942b3e8a066f776d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":419,
              "y":980},
            "size":{
              "width":31,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b43636076ab446a18f068e9ed3f17a2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":419,
                  "y":980},
                "size":{
                  "width":31,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35da0094ed4a4f259a531c7c1df8a797",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":560,
              "y":980},
            "size":{
              "width":16,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01713ce83bcf4091a77d65ab5c960507",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":560,
                  "y":980},
                "size":{
                  "width":16,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5107a10785ac44f2a635c889d1f6d16c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":1020},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f49bb9171914152aed6ee69ea297316",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":1020},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "76ce45d76eba45c293a7df57f31a3de3":{
      "scriptId":"u0"},
    "05dbaf0bd2cb4953abc634f4fb0d5fdb":{
      "scriptId":"u1"},
    "0a7d680cc7564bd39bd0ee16eac3cb95":{
      "scriptId":"u2"},
    "0ba26f1e7e2f469497ef8c88097dc63e":{
      "scriptId":"u3"},
    "991df3d3fdd1451d8aced3169a5bc789":{
      "scriptId":"u4"},
    "b015a1a3504440109552d06f28c76bcf":{
      "scriptId":"u5"},
    "d298b14c272749b8a4f4f7293d74e4c7":{
      "scriptId":"u6"},
    "4e01a222b6bd4ad588a338a7f8b83439":{
      "scriptId":"u7"},
    "7a577ba0324844de8ae3ff99717ea2ab":{
      "scriptId":"u8"},
    "ef71d71c3b1b440abeace360dce742a5":{
      "scriptId":"u9"},
    "378028515296403ea5a6b5a9a95f4612":{
      "scriptId":"u10"},
    "80d6c4e6a9d1498e9666f92de7d8584b":{
      "scriptId":"u11"},
    "eccb4ed251c34d9ca9fd16bdaeb07fad":{
      "scriptId":"u12"},
    "921fc1de3eff44bc908aa0baae839746":{
      "scriptId":"u13"},
    "d610c665b54241268c1e6a79c31f605b":{
      "scriptId":"u14"},
    "ee286d647f03492c80c508b7c1b1ff16":{
      "scriptId":"u15"},
    "287731c279f746938cf18aac48481c01":{
      "scriptId":"u16"},
    "70d13ca0426445a8af5552af97cfdad8":{
      "scriptId":"u17"},
    "23991922d5c24a9d823815ef8651849d":{
      "scriptId":"u18"},
    "bc0027e6bbfd41259f467211952d56b9":{
      "scriptId":"u19"},
    "f61cd3b5b3d54d6fa55d074c349c46d4":{
      "scriptId":"u20"},
    "b703881e160c4b6fbf6975d7fa812b5c":{
      "scriptId":"u21"},
    "be6a2648bce545d18ba7b299b8f98b17":{
      "scriptId":"u22"},
    "0b378058fdfc4bc9a3c0932ba2bdd6ec":{
      "scriptId":"u23"},
    "8b39fe13cde64a919e48f735970606fc":{
      "scriptId":"u24"},
    "55e7c44975b14ccd852556152e05a341":{
      "scriptId":"u25"},
    "c42bdfc0f0254d1cb4d59b10ef73d42b":{
      "scriptId":"u26"},
    "c0e4043c56844c9d8306a87ef7117e07":{
      "scriptId":"u27"},
    "00a78dcb3aa14da8af36fe5da7620c11":{
      "scriptId":"u28"},
    "808cc2b0c4c1476580a3111c19240a2b":{
      "scriptId":"u29"},
    "17f17e00c7224cf89a4fdad994df82ce":{
      "scriptId":"u30"},
    "4efcfee4aad84e64a168231eeda683c1":{
      "scriptId":"u31"},
    "78714c60afd1494291a04eab128658cc":{
      "scriptId":"u32"},
    "08e24ac2b2db49c486124add92004211":{
      "scriptId":"u33"},
    "36ff1d2bca9d48b3b9f4025d566e72f2":{
      "scriptId":"u34"},
    "06b4c77f2fec44fcb25d433dfe88aabc":{
      "scriptId":"u35"},
    "deed9300e1414cada534422dc7ebb5fb":{
      "scriptId":"u36"},
    "fc3c4293c8474c3aa27fc226d57415a6":{
      "scriptId":"u37"},
    "7fdff4249e394d2190911e7cdec6746a":{
      "scriptId":"u38"},
    "a672daa021bb40238e963822227aa343":{
      "scriptId":"u39"},
    "affee51f3e0743ebbd457cb605c219c6":{
      "scriptId":"u40"},
    "92703f2178444e618728c58e18cbeb72":{
      "scriptId":"u41"},
    "e53e164893224100bafb8014a2e7c09f":{
      "scriptId":"u42"},
    "2a4060585a8e42208aad3e5f4fe104f0":{
      "scriptId":"u43"},
    "08b30d778d4146458b17269b35af081b":{
      "scriptId":"u44"},
    "754a981b38284ad7873fe3dc0ad34027":{
      "scriptId":"u45"},
    "0a2eaa2bc1fe42b9bd997982bede33cd":{
      "scriptId":"u46"},
    "daa7e0de26f5464dbacb5217579023fc":{
      "scriptId":"u47"},
    "0261ec6d86ac4004ab5c9696c59d9eb4":{
      "scriptId":"u48"},
    "d319782261be489190b490096856384e":{
      "scriptId":"u49"},
    "77d72ec1c3a349a9ad6d480d1781655b":{
      "scriptId":"u50"},
    "c06e4d17c00c4833b9792ebd6db2f410":{
      "scriptId":"u51"},
    "1a409df8270b44c68834c5e67261ad47":{
      "scriptId":"u52"},
    "82402d2ddb4f4fa68192845958474246":{
      "scriptId":"u53"},
    "0c5e7e33a49149ad8e5f6b9531c2bab9":{
      "scriptId":"u54"},
    "a0629dc0a2354ab59596c9426d473175":{
      "scriptId":"u55"},
    "781417202127433d91c90039a0c79d99":{
      "scriptId":"u56"},
    "345949d099bb45e693906837d9ab773a":{
      "scriptId":"u57"},
    "0e0b64b7067b4e59b665aaed1cd13e9d":{
      "scriptId":"u58"},
    "94de85dc16a0492aa3a2cefc956ee579":{
      "scriptId":"u59"},
    "6b5a93a7c245477da6fe09ee965c63f2":{
      "scriptId":"u60"},
    "aa5cd4c6667344ab85d4400ff6f988bd":{
      "scriptId":"u61"},
    "209f2afae7d54dfda4695eb4a7ff5ad5":{
      "scriptId":"u62"},
    "5d1cd12ae8ff4101a14607a19bfddf6b":{
      "scriptId":"u63"},
    "9c5e36a6eb854df19d4693ba2cc50794":{
      "scriptId":"u64"},
    "78f6849e84ed49c689c7d0cdcadccef7":{
      "scriptId":"u65"},
    "9cdc44f923694b649c13188b40b5512e":{
      "scriptId":"u66"},
    "58bb62d8a037428aab9feea37ef6835f":{
      "scriptId":"u67"},
    "a4d02876922a428c995bd495c87acbe0":{
      "scriptId":"u68"},
    "011e4a5ba16848858a355c7cdedf7fce":{
      "scriptId":"u69"},
    "eee013474e164fb8a1037856f495ae88":{
      "scriptId":"u70"},
    "0865de68082b4dd8a79009c1583379b4":{
      "scriptId":"u71"},
    "1d99cfe79ce041438eebe7c2545f84e0":{
      "scriptId":"u72"},
    "0b677ba267614523a4166838ff2c2286":{
      "scriptId":"u73"},
    "6b5e216602e647dd85d5b80443f2957a":{
      "scriptId":"u74"},
    "b162ff98717c497a9ef1e2dd3342ba35":{
      "scriptId":"u75"},
    "1f78bccb075740b3858f9079d3836971":{
      "scriptId":"u76"},
    "c9b3863c62a9460c82a4d4ddc0accc61":{
      "scriptId":"u77"},
    "0f0ea47789f7445ea5ac6cbc8f315dd6":{
      "scriptId":"u78"},
    "fe82fbbb26814c129e25a7a17f3def2a":{
      "scriptId":"u79"},
    "7adbb4e42bfe46f5997b5410e1ffb9cb":{
      "scriptId":"u80"},
    "3cc9360ed9284d2ca2a3a307bd8ad9e5":{
      "scriptId":"u81"},
    "a8b19ad5e5af4d23bcc88faca6ef7370":{
      "scriptId":"u82"},
    "e13cd3edcc394881b7efd6fa1dd960dd":{
      "scriptId":"u83"},
    "97889e67f8c746e086ae13ac0d3d28e8":{
      "scriptId":"u84"},
    "0ffbf011dc2448b8831491a39041ec80":{
      "scriptId":"u85"},
    "d86173fbb7b147c399db749da8d92cd3":{
      "scriptId":"u86"},
    "4dc9f7b401e04640ac943787671dfe4b":{
      "scriptId":"u87"},
    "3a54e47753ba4d1dae85979dd448217c":{
      "scriptId":"u88"},
    "e71fc08ef29a4c8f8641153b23bfb9ad":{
      "scriptId":"u89"},
    "aa46eec356b84786a9d6da1a08b619b9":{
      "scriptId":"u90"},
    "2ef766213d6e42ee8faa03267f5f61ed":{
      "scriptId":"u91"},
    "da105fefaf164d9ea8c9a42dfc1f4747":{
      "scriptId":"u92"},
    "4cd8c6da91f741059975346972be2271":{
      "scriptId":"u93"},
    "57254ff7033f4571a87a7401f30dd62d":{
      "scriptId":"u94"},
    "499884b4b01d481880d6dc0d0b79ffad":{
      "scriptId":"u95"},
    "68c25f815e7f4eeb962f093064b3d743":{
      "scriptId":"u96"},
    "967fe0161e6249a99a83446370b93282":{
      "scriptId":"u97"},
    "cd2cdfc280ef4615b74b5732eccc45dc":{
      "scriptId":"u98"},
    "c534f6a1084d42fda1bddc65ea33d1fc":{
      "scriptId":"u99"},
    "62cefb68252f4d1f9509d3bdcb561ebb":{
      "scriptId":"u100"},
    "0dc1fbcf0d294a59991151f0410fde42":{
      "scriptId":"u101"},
    "45a8ff54ea0744eea2a3d3d81404c26b":{
      "scriptId":"u102"},
    "7f0f47a790e04183b2b88aad182c9ae7":{
      "scriptId":"u103"},
    "0d1c054b2b4c4439920d47d0a7180b86":{
      "scriptId":"u104"},
    "bc86b01829d14fbda4b2ac49625ace02":{
      "scriptId":"u105"},
    "c5aafb758d7e402eb0d7dd312d0f408e":{
      "scriptId":"u106"},
    "9a833e42748141f6912488c6aed06e87":{
      "scriptId":"u107"},
    "014a7d1e4b254a0185532b13d4994d0b":{
      "scriptId":"u108"},
    "7202b065ad784facb0fd463be99df706":{
      "scriptId":"u109"},
    "da4bdd8c611d417595ef7011a62bf893":{
      "scriptId":"u110"},
    "70b41457bc8844878c658b096b878d19":{
      "scriptId":"u111"},
    "c9330a8610b64500bf65498310ab6a3e":{
      "scriptId":"u112"},
    "7adaf6eaa2e84fcdad8892ec9743e1a1":{
      "scriptId":"u113"},
    "1a8c9769b5154b8c8219763bca2b9d9e":{
      "scriptId":"u114"},
    "477e88052b644543aafe27adb894cea1":{
      "scriptId":"u115"},
    "ee8e416ddb474faaab3926fd6789b59a":{
      "scriptId":"u116"},
    "f944c126cb0642a0b0af3ae24f6f8f2b":{
      "scriptId":"u117"},
    "f9c358c86a0c41a6b43f9a95584ad30e":{
      "scriptId":"u118"},
    "4a983458c40343b9b4aee26d11450742":{
      "scriptId":"u119"},
    "e2ab2825dddd4cf2a6bbc107f754a233":{
      "scriptId":"u120"},
    "350d5e2c71f14f70b2526b42c742f37f":{
      "scriptId":"u121"},
    "509aa448090c422eaaf960b0ce1e37d3":{
      "scriptId":"u122"},
    "704247ecd9dc495084fc671bbb2dc854":{
      "scriptId":"u123"},
    "01845ae16c4b4a0782ed058ff1ee4daf":{
      "scriptId":"u124"},
    "e8bd3957e89e490b8b050ab6b0106b64":{
      "scriptId":"u125"},
    "84f8508553674621a358e1bcdc4d7004":{
      "scriptId":"u126"},
    "fb0001e9c33046a09eec667383441904":{
      "scriptId":"u127"},
    "25213b69fa3b4024ae8dc2597608bd9d":{
      "scriptId":"u128"},
    "1488d768b1a24074b43b6527479612ad":{
      "scriptId":"u129"},
    "17ccfa1ce43a40879363b5b89983d0f7":{
      "scriptId":"u130"},
    "0ff1f7345e494ed1a7d9fa1ab3c06140":{
      "scriptId":"u131"},
    "8c71d8b43e31403a942b3e8a066f776d":{
      "scriptId":"u132"},
    "b43636076ab446a18f068e9ed3f17a2f":{
      "scriptId":"u133"},
    "35da0094ed4a4f259a531c7c1df8a797":{
      "scriptId":"u134"},
    "01713ce83bcf4091a77d65ab5c960507":{
      "scriptId":"u135"},
    "5107a10785ac44f2a635c889d1f6d16c":{
      "scriptId":"u136"},
    "3f49bb9171914152aed6ee69ea297316":{
      "scriptId":"u137"}}});