$axure.loadCurrentPage({
  "url":"找回密码1_ok.html",
  "generationDate":new Date(1496627733442.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"09f6e1bb759e4a1f9f34ecdc4c1c8b02",
    "type":"Axure:Page",
    "name":"找回密码1 ok",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFD7D7D7},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f13978f338884f20bb55da80cd72c4c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04c47598e0dc4ecba124d773218a48fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u1.png"}},
{
          "id":"4486806410e04d2394d165674f3eda96",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ba6eccbf0ea42a597971302cf2beeea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u3.png"}},
{
          "id":"a4356735a3074afa9230c9e5cd34e24a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":28},
            "size":{
              "width":22,
              "height":22},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b6ffed3b9c14d2392bf4dd6440a286e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":28},
                "size":{
                  "width":22,
                  "height":22},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录ok",
                      "target":{
                        "targetType":"page",
                        "url":"登录ok.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动页ok/u47.png"}},
{
          "id":"99f10736259148dcb949cf4578659561",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":50},
            "size":{
              "width":358,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录ok/u20_line.png"}},
{
          "id":"a541cfa7f22f47d9b8dedec1abd71520",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":184},
            "size":{
              "width":264,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录ok/u21_line.png"}},
{
          "id":"64111bb433e4477fb1ff27973abaf796",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":60,
              "y":169},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8424e9f07c8b44a2ac136184dbd3252b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":169},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e81be905f71e4c5494138d7cb2286253",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":139,
              "y":279},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76ef322ff588487d8bf600780124ef10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":139,
                  "y":279},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e34003503ac409ca57aa5b06ab62bf8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":139,
              "y":299},
            "size":{
              "width":91,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/找回密码1_ok/u12_line.png"}},
{
          "id":"e8969f90a1e5428eb896a0246814b823",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":160,
              "y":31},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80a45f08a9d64137854a186edb801fb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":160,
                  "y":31},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5fb5eb1813742779aa6cf60b50fccc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":103},
            "size":{
              "width":183,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c98d6de828b84c62bd15826c6d24810c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":103},
                "size":{
                  "width":183,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a0a9e74f4f3433d9be9c27c8b6c4640",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":33},
            "size":{
              "width":414,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/更新加载/u196_end.png",
            "line~":"images/跳转到微信登录页ok/u19_line.png"}},
{
          "id":"1d3c04b6c0eb4665a4c5f6e67a1db7c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "location":{
              "x":24,
              "y":35},
            "size":{
              "width":6,
              "height":6},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "cornerRadiusTopLeft":"3.5",
            "outerShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":3,
              "color":{
                "r":39,
                "g":162,
                "b":252,
                "a":0.447058823529412}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09e0e4792ccc471891fe55719e1a6ea0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "location":{
                  "x":24,
                  "y":35},
                "size":{
                  "width":6,
                  "height":6},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "cornerRadiusTopLeft":"3.5",
                "outerShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":3,
                  "color":{
                    "r":39,
                    "g":162,
                    "b":252,
                    "a":0.447058823529412}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u197.png"}},
{
          "id":"37984b59888d46448c187906c499a01f",
          "label":"Header 2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":452,
              "y":28},
            "size":{
              "width":99,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94a403f04e194ff8a4b991bc49db9b17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":452,
                  "y":28},
                "size":{
                  "width":99,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a86b8c1d862849dc8eb79b525de53297",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":284},
            "size":{
              "width":212,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/更新加载/u196_end.png",
            "line~":"images/启动页ok/u35_line.png"}},
{
          "id":"3331240d3ae447b1bc4f34367172f4f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "location":{
              "x":224,
              "y":286},
            "size":{
              "width":6,
              "height":6},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "cornerRadiusTopLeft":"3.5",
            "outerShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":3,
              "color":{
                "r":39,
                "g":162,
                "b":252,
                "a":0.447058823529412}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ccbf4aab5b9429ebce03646f0059350",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "location":{
                  "x":224,
                  "y":286},
                "size":{
                  "width":6,
                  "height":6},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "cornerRadiusTopLeft":"3.5",
                "outerShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":3,
                  "color":{
                    "r":39,
                    "g":162,
                    "b":252,
                    "a":0.447058823529412}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u197.png"}},
{
          "id":"b8df2158ea2f4b2e9227127876b6a28d",
          "label":"Header 2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":452,
              "y":279},
            "size":{
              "width":141,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4319d448467f4373a48bdc65c6736f35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":452,
                  "y":279},
                "size":{
                  "width":141,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"706eb546fcb54cb495ad0127282b7929",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":712},
            "size":{
              "width":710,
              "height":198}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c735a15116e849e484c9c00531a47546",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"350bcc51ed6d45758241ab015216ad19",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/登录ok/u31.png"}},
{
              "id":"b1534f879a2b4328b3a7a8a5494a271b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":84}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2bfb561023774b9f8d3fcf72bea96b3d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":84}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册ok/u89.png"}},
{
              "id":"1331af867cf34c689859d12e29fefa2b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":319,
                  "y":0},
                "size":{
                  "width":112,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e8fd93705ae74c4588bc02f2e83c8359",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":319,
                      "y":0},
                    "size":{
                      "width":112,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/找回密码1_ok/u32.png"}},
{
              "id":"afa1569635234f2da80fa814e280f8b7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":319,
                  "y":30},
                "size":{
                  "width":112,
                  "height":84}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"00568a23cd9d4ab3a19e37c40d0a75e1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":319,
                      "y":30},
                    "size":{
                      "width":112,
                      "height":84}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/找回密码1_ok/u42.png"}},
{
              "id":"968ff433e76a4c20a6e7f9f2ab7f3dcd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":431,
                  "y":0},
                "size":{
                  "width":137,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d26faace2cc94316aa40c507ada2ba42",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":431,
                      "y":0},
                    "size":{
                      "width":137,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/找回密码1_ok/u34.png"}},
{
              "id":"1fc9dc9293ef4f01a618f26586f60b2a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":431,
                  "y":30},
                "size":{
                  "width":137,
                  "height":84}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dceea4f1b64a43eb98257fabbea5fada",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":431,
                      "y":30},
                    "size":{
                      "width":137,
                      "height":84}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册ok/u93.png"}},
{
              "id":"4f878cdd0fa64cd2b043b577d74ad0b9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":568,
                  "y":0},
                "size":{
                  "width":142,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"99c1180912ba4e76854205ce47265179",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":568,
                      "y":0},
                    "size":{
                      "width":142,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/登录ok/u144.png"}},
{
              "id":"7d80ecfe0a2b4029ba1ce8b42d9076ab",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":568,
                  "y":30},
                "size":{
                  "width":142,
                  "height":84}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"72c0c7637efd412381f9af13199533e9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":568,
                      "y":30},
                    "size":{
                      "width":142,
                      "height":84}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/找回密码1_ok/u46.png"}},
{
              "id":"d9e9452ee2394dfb9664ad232f98e443",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":219,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"166365a356754512a0f63caa5c43ba37",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":219,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/找回密码1_ok/u30.png"}},
{
              "id":"2f89f0fee65946abbeebd70bda0e9387",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":219,
                  "height":84}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d2ed3c8ec78b496f9f792fc4ad07d6b2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":219,
                      "height":84}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/找回密码1_ok/u40.png"}},
{
              "id":"8aa5800a8cae4ff3a0b79fc17ada510d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":114},
                "size":{
                  "width":100,
                  "height":84}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e4ba448a44db48269f89a25fb8fe3faa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":0,
                      "y":114},
                    "size":{
                      "width":100,
                      "height":84}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/找回密码1_ok/u48.png"}},
{
              "id":"bef47416fdd14f86ab78ff885e738129",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":114},
                "size":{
                  "width":219,
                  "height":84}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f6f2a4e4cb294e798cbbb0071663bc5f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":114},
                    "size":{
                      "width":219,
                      "height":84}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/找回密码1_ok/u50.png"}},
{
              "id":"6000749c1687415389d2d680f9175178",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":319,
                  "y":114},
                "size":{
                  "width":112,
                  "height":84}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1e9c2b5088c14094bb4361733368c417",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":319,
                      "y":114},
                    "size":{
                      "width":112,
                      "height":84}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/找回密码1_ok/u52.png"}},
{
              "id":"a5508e8fb9e048dd82cec0980981a091",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":431,
                  "y":114},
                "size":{
                  "width":137,
                  "height":84}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4da823b4b56141289c046ec7fb8878a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":431,
                      "y":114},
                    "size":{
                      "width":137,
                      "height":84}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/找回密码1_ok/u54.png"}},
{
              "id":"f55427d165764e75ae48751a7ce8ecd8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":568,
                  "y":114},
                "size":{
                  "width":142,
                  "height":84}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"55cfff5627d7461a88ed608a17013ec6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":568,
                      "y":114},
                    "size":{
                      "width":142,
                      "height":84}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/找回密码1_ok/u56.png"}}]},
{
          "id":"fbfe7972489a4d579d16caefb5f3c538",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xBF333333},
            "location":{
              "x":510,
              "y":574},
            "size":{
              "width":200,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7aeb484d9ed14714a4af6504ad762004",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xBF333333},
                "location":{
                  "x":510,
                  "y":574},
                "size":{
                  "width":200,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录ok/u123.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f13978f338884f20bb55da80cd72c4c5":{
      "scriptId":"u0"},
    "04c47598e0dc4ecba124d773218a48fe":{
      "scriptId":"u1"},
    "4486806410e04d2394d165674f3eda96":{
      "scriptId":"u2"},
    "4ba6eccbf0ea42a597971302cf2beeea":{
      "scriptId":"u3"},
    "a4356735a3074afa9230c9e5cd34e24a":{
      "scriptId":"u4"},
    "4b6ffed3b9c14d2392bf4dd6440a286e":{
      "scriptId":"u5"},
    "99f10736259148dcb949cf4578659561":{
      "scriptId":"u6"},
    "a541cfa7f22f47d9b8dedec1abd71520":{
      "scriptId":"u7"},
    "64111bb433e4477fb1ff27973abaf796":{
      "scriptId":"u8"},
    "8424e9f07c8b44a2ac136184dbd3252b":{
      "scriptId":"u9"},
    "e81be905f71e4c5494138d7cb2286253":{
      "scriptId":"u10"},
    "76ef322ff588487d8bf600780124ef10":{
      "scriptId":"u11"},
    "1e34003503ac409ca57aa5b06ab62bf8":{
      "scriptId":"u12"},
    "e8969f90a1e5428eb896a0246814b823":{
      "scriptId":"u13"},
    "80a45f08a9d64137854a186edb801fb2":{
      "scriptId":"u14"},
    "e5fb5eb1813742779aa6cf60b50fccc4":{
      "scriptId":"u15"},
    "c98d6de828b84c62bd15826c6d24810c":{
      "scriptId":"u16"},
    "0a0a9e74f4f3433d9be9c27c8b6c4640":{
      "scriptId":"u17"},
    "1d3c04b6c0eb4665a4c5f6e67a1db7c3":{
      "scriptId":"u18"},
    "09e0e4792ccc471891fe55719e1a6ea0":{
      "scriptId":"u19"},
    "37984b59888d46448c187906c499a01f":{
      "scriptId":"u20"},
    "94a403f04e194ff8a4b991bc49db9b17":{
      "scriptId":"u21"},
    "a86b8c1d862849dc8eb79b525de53297":{
      "scriptId":"u22"},
    "3331240d3ae447b1bc4f34367172f4f9":{
      "scriptId":"u23"},
    "3ccbf4aab5b9429ebce03646f0059350":{
      "scriptId":"u24"},
    "b8df2158ea2f4b2e9227127876b6a28d":{
      "scriptId":"u25"},
    "4319d448467f4373a48bdc65c6736f35":{
      "scriptId":"u26"},
    "706eb546fcb54cb495ad0127282b7929":{
      "scriptId":"u27"},
    "c735a15116e849e484c9c00531a47546":{
      "scriptId":"u28"},
    "350bcc51ed6d45758241ab015216ad19":{
      "scriptId":"u29"},
    "d9e9452ee2394dfb9664ad232f98e443":{
      "scriptId":"u30"},
    "166365a356754512a0f63caa5c43ba37":{
      "scriptId":"u31"},
    "1331af867cf34c689859d12e29fefa2b":{
      "scriptId":"u32"},
    "e8fd93705ae74c4588bc02f2e83c8359":{
      "scriptId":"u33"},
    "968ff433e76a4c20a6e7f9f2ab7f3dcd":{
      "scriptId":"u34"},
    "d26faace2cc94316aa40c507ada2ba42":{
      "scriptId":"u35"},
    "4f878cdd0fa64cd2b043b577d74ad0b9":{
      "scriptId":"u36"},
    "99c1180912ba4e76854205ce47265179":{
      "scriptId":"u37"},
    "b1534f879a2b4328b3a7a8a5494a271b":{
      "scriptId":"u38"},
    "2bfb561023774b9f8d3fcf72bea96b3d":{
      "scriptId":"u39"},
    "2f89f0fee65946abbeebd70bda0e9387":{
      "scriptId":"u40"},
    "d2ed3c8ec78b496f9f792fc4ad07d6b2":{
      "scriptId":"u41"},
    "afa1569635234f2da80fa814e280f8b7":{
      "scriptId":"u42"},
    "00568a23cd9d4ab3a19e37c40d0a75e1":{
      "scriptId":"u43"},
    "1fc9dc9293ef4f01a618f26586f60b2a":{
      "scriptId":"u44"},
    "dceea4f1b64a43eb98257fabbea5fada":{
      "scriptId":"u45"},
    "7d80ecfe0a2b4029ba1ce8b42d9076ab":{
      "scriptId":"u46"},
    "72c0c7637efd412381f9af13199533e9":{
      "scriptId":"u47"},
    "8aa5800a8cae4ff3a0b79fc17ada510d":{
      "scriptId":"u48"},
    "e4ba448a44db48269f89a25fb8fe3faa":{
      "scriptId":"u49"},
    "bef47416fdd14f86ab78ff885e738129":{
      "scriptId":"u50"},
    "f6f2a4e4cb294e798cbbb0071663bc5f":{
      "scriptId":"u51"},
    "6000749c1687415389d2d680f9175178":{
      "scriptId":"u52"},
    "1e9c2b5088c14094bb4361733368c417":{
      "scriptId":"u53"},
    "a5508e8fb9e048dd82cec0980981a091":{
      "scriptId":"u54"},
    "4da823b4b56141289c046ec7fb8878a3":{
      "scriptId":"u55"},
    "f55427d165764e75ae48751a7ce8ecd8":{
      "scriptId":"u56"},
    "55cfff5627d7461a88ed608a17013ec6":{
      "scriptId":"u57"},
    "fbfe7972489a4d579d16caefb5f3c538":{
      "scriptId":"u58"},
    "7aeb484d9ed14714a4af6504ad762004":{
      "scriptId":"u59"}}});