$axure.loadCurrentPage({
  "url":"跳转到微信登录页ok.html",
  "generationDate":new Date(1496627732695.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"593fff00cdd149fd81c0f8c8a8fb0394",
    "type":"Axure:Page",
    "name":"跳转到微信登录页ok",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFD7D7D7},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1c79730324d645f9b1cfc2eee0538253",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1d01f310c264c75a0d4adba199cb2d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u1.png"}},
{
          "id":"d9c109aafa9d476ab1f3633c36d32877",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d505909f770c428282444ae5bfadc138",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u3.png"}},
{
          "id":"1f98163a6fee46fbb8c6bbf3954ddd42",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":30},
            "size":{
              "width":22,
              "height":22},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30d6ca8f973f46459b7c8b844effe62f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":30},
                "size":{
                  "width":22,
                  "height":22},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页ok/u47.png"}},
{
          "id":"c81ef85305ac4fbc8903b6c7dada3a71",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":52},
            "size":{
              "width":358,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录ok/u20_line.png"}},
{
          "id":"fe1be5bd11104690946890591badb76e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":170},
            "size":{
              "width":200,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d2aceb42a884636b18f52ba4dd9332b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":170},
                "size":{
                  "width":200,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/跳转到微信登录页ok/u7.png"}},
{
          "id":"3b623f0e96894eeead488e294654f53c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":33},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f80b9427604d4db09b0200b6caeb1b6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":33},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04278241cc9f4d9596e9f4165e01dba1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":235},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页(精选)ok",
                      "target":{
                        "targetType":"page",
                        "url":"首页_精选_ok.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8ab7e4ce0caf4bf4a2a00037fe791e2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":184},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dff38370be64ba1847c86952bd0c21e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":184},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ed456324d454f3f8761c3ce641f7021",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":224,
              "y":246},
            "size":{
              "width":212,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/更新加载/u196_end.png",
            "line~":"images/启动页ok/u35_line.png"}},
{
          "id":"0e9bb4b2212e4ece8410fa9c8909e9e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "location":{
              "x":220,
              "y":248},
            "size":{
              "width":6,
              "height":6},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "cornerRadiusTopLeft":"3.5",
            "outerShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":3,
              "color":{
                "r":39,
                "g":162,
                "b":252,
                "a":0.447058823529412}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be52d06b382e466096f0757b6598f3fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "location":{
                  "x":220,
                  "y":248},
                "size":{
                  "width":6,
                  "height":6},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "cornerRadiusTopLeft":"3.5",
                "outerShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":3,
                  "color":{
                    "r":39,
                    "g":162,
                    "b":252,
                    "a":0.447058823529412}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u197.png"}},
{
          "id":"221d33262aa446eea4b83079af2dc372",
          "label":"Header 2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":452,
              "y":242},
            "size":{
              "width":127,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f507f1cb45c54f73b8be5210847cd5c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":452,
                  "y":242},
                "size":{
                  "width":127,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82f1f94568834235984403c044842bab",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":36},
            "size":{
              "width":414,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/更新加载/u196_end.png",
            "line~":"images/跳转到微信登录页ok/u19_line.png"}},
{
          "id":"d4d87d09051543c5af20f961138a228d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "location":{
              "x":24,
              "y":38},
            "size":{
              "width":6,
              "height":6},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "cornerRadiusTopLeft":"3.5",
            "outerShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":3,
              "color":{
                "r":39,
                "g":162,
                "b":252,
                "a":0.447058823529412}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f991221b333b4708b6a23aef6a6aa1dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "location":{
                  "x":24,
                  "y":38},
                "size":{
                  "width":6,
                  "height":6},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "cornerRadiusTopLeft":"3.5",
                "outerShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":3,
                  "color":{
                    "r":39,
                    "g":162,
                    "b":252,
                    "a":0.447058823529412}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u197.png"}},
{
          "id":"ef4ecd3acede41d69971848071680834",
          "label":"Header 2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":452,
              "y":32},
            "size":{
              "width":127,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"285ec9ec3b234097a0b1d644c64a19d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":452,
                  "y":32},
                "size":{
                  "width":127,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9817e8beef184d0aae281b70f24c759f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":7},
            "size":{
              "width":414,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/更新加载/u196_end.png",
            "line~":"images/跳转到微信登录页ok/u19_line.png"}},
{
          "id":"163fba6197044aa7a68c18ef8bbfe571",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "location":{
              "x":24,
              "y":9},
            "size":{
              "width":6,
              "height":6},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "cornerRadiusTopLeft":"3.5",
            "outerShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":3,
              "color":{
                "r":39,
                "g":162,
                "b":252,
                "a":0.447058823529412}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e251c885bdeb4c59acd109245b0e7c5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "location":{
                  "x":24,
                  "y":9},
                "size":{
                  "width":6,
                  "height":6},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "cornerRadiusTopLeft":"3.5",
                "outerShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":3,
                  "color":{
                    "r":39,
                    "g":162,
                    "b":252,
                    "a":0.447058823529412}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u197.png"}},
{
          "id":"3d4d72efc3c3401caf855878997e8a67",
          "label":"Header 2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":452,
              "y":3},
            "size":{
              "width":127,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4ba57b38bc9445dac7698da0db82a41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":452,
                  "y":3},
                "size":{
                  "width":127,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1c79730324d645f9b1cfc2eee0538253":{
      "scriptId":"u0"},
    "b1d01f310c264c75a0d4adba199cb2d9":{
      "scriptId":"u1"},
    "d9c109aafa9d476ab1f3633c36d32877":{
      "scriptId":"u2"},
    "d505909f770c428282444ae5bfadc138":{
      "scriptId":"u3"},
    "1f98163a6fee46fbb8c6bbf3954ddd42":{
      "scriptId":"u4"},
    "30d6ca8f973f46459b7c8b844effe62f":{
      "scriptId":"u5"},
    "c81ef85305ac4fbc8903b6c7dada3a71":{
      "scriptId":"u6"},
    "fe1be5bd11104690946890591badb76e":{
      "scriptId":"u7"},
    "4d2aceb42a884636b18f52ba4dd9332b":{
      "scriptId":"u8"},
    "3b623f0e96894eeead488e294654f53c":{
      "scriptId":"u9"},
    "f80b9427604d4db09b0200b6caeb1b6f":{
      "scriptId":"u10"},
    "04278241cc9f4d9596e9f4165e01dba1":{
      "scriptId":"u11"},
    "8ab7e4ce0caf4bf4a2a00037fe791e2a":{
      "scriptId":"u12"},
    "4dff38370be64ba1847c86952bd0c21e":{
      "scriptId":"u13"},
    "6ed456324d454f3f8761c3ce641f7021":{
      "scriptId":"u14"},
    "0e9bb4b2212e4ece8410fa9c8909e9e3":{
      "scriptId":"u15"},
    "be52d06b382e466096f0757b6598f3fd":{
      "scriptId":"u16"},
    "221d33262aa446eea4b83079af2dc372":{
      "scriptId":"u17"},
    "f507f1cb45c54f73b8be5210847cd5c6":{
      "scriptId":"u18"},
    "82f1f94568834235984403c044842bab":{
      "scriptId":"u19"},
    "d4d87d09051543c5af20f961138a228d":{
      "scriptId":"u20"},
    "f991221b333b4708b6a23aef6a6aa1dc":{
      "scriptId":"u21"},
    "ef4ecd3acede41d69971848071680834":{
      "scriptId":"u22"},
    "285ec9ec3b234097a0b1d644c64a19d5":{
      "scriptId":"u23"},
    "9817e8beef184d0aae281b70f24c759f":{
      "scriptId":"u24"},
    "163fba6197044aa7a68c18ef8bbfe571":{
      "scriptId":"u25"},
    "e251c885bdeb4c59acd109245b0e7c5d":{
      "scriptId":"u26"},
    "3d4d72efc3c3401caf855878997e8a67":{
      "scriptId":"u27"},
    "e4ba57b38bc9445dac7698da0db82a41":{
      "scriptId":"u28"}}});