$axure.loadCurrentPage({
  "url":"启动页ok.html",
  "generationDate":new Date(1500893905389.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bae2d1842e924db4a8f5ba68aa3ce29a",
    "type":"Axure:Page",
    "name":"启动页ok",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c9e5fce28c6245e785a06b42b74654b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7b345348d06412081bb774a265685d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u1.png"}},
{
          "id":"7fc22ccc670c47b9a00e25ea512a43a0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d156f962f72444b9bc6b6dc6c5cf3cf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u3.png"}},
{
          "id":"ff035463188a4f4abd8a22bb1db33bb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":723},
            "size":{
              "width":481,
              "height":48},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9da4a964fea54056804552b95f5194fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":0,
                  "y":723},
                "size":{
                  "width":481,
                  "height":48},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c8ca4c1a3544d4f86d1a89d57ff0f17",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":771},
            "size":{
              "width":190,
              "height":64},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8da74b7ed7748da95120cffee2331cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":0,
                  "y":771},
                "size":{
                  "width":190,
                  "height":64},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5a07e2f597143b4a2deeef9fa51f401",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":131,
              "y":437},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51644cbcb417499d9979154f0c79210a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":131,
                  "y":437},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f41a558b4a8541528b9702b29c287a22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":860,
              "y":360},
            "size":{
              "width":144,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9ffab0015d2431bb6d9febd65ab52c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":860,
                  "y":360},
                "size":{
                  "width":144,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d0ed5cb90a44426a8cbeba5a5a9d14c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":88,
              "y":227},
            "size":{
              "width":200,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adf1d25756294e28b30c955610a557d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":88,
                  "y":227},
                "size":{
                  "width":200,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页ok/u12.png"}},
{
          "id":"85bfc87109134410ac3902ec222131fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":0,
              "y":880},
            "size":{
              "width":392,
              "height":48},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b023da5bd35547048213aed01adc3624",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":0,
                  "y":880},
                "size":{
                  "width":392,
                  "height":48},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26a23776a4ae4e35a71930ff049ba4fd",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":227},
            "size":{
              "width":200,
              "height":200}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页(精选)ok",
                      "target":{
                        "targetType":"page",
                        "url":"首页_精选_ok.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"86181c1128e84caf82be480085ba3caf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":642,
              "y":334},
            "size":{
              "width":118,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2952ef00517a404abdcb369a7f6dae7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":642,
                  "y":334},
                "size":{
                  "width":118,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"778918e5b4774a87852dc3646e888a66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":420,
              "y":360},
            "size":{
              "width":144,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57b830aebb3a43ba8467621ad225a89a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":420,
                  "y":360},
                "size":{
                  "width":144,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc00a64922ec473cbed831c209d524af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":420,
              "y":334},
            "size":{
              "width":144,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4215e104dc944d838b5480af29c1d096",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":420,
                  "y":334},
                "size":{
                  "width":144,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f66f9342955e4405bcfec63fd4db3786",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":860,
              "y":334},
            "size":{
              "width":144,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa470962eb4e4c9392169a4f18cf9fad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":860,
                  "y":334},
                "size":{
                  "width":144,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae18a5e724c049519faead8d458048f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":420,
              "y":308},
            "size":{
              "width":53,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84dcfc4b57084a6fa8e7cd208cee30b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":420,
                  "y":308},
                "size":{
                  "width":53,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"677400aa52704a80aab463888d8b5d6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":642,
              "y":360},
            "size":{
              "width":183,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"faec525d1d8647139f54ee7b9dc097be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":642,
                  "y":360},
                "size":{
                  "width":183,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d31e612b72dd44b5b454e99e8cac349f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":642,
              "y":308},
            "size":{
              "width":53,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40ad7a08971b42a881a58211fcc2cc3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":642,
                  "y":308},
                "size":{
                  "width":53,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c4c0f14808c4d2b9e80c8e08f78d954",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":860,
              "y":308},
            "size":{
              "width":53,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"166accc78c79416a9f2cb2c71cdda0d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":860,
                  "y":308},
                "size":{
                  "width":53,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02584fdca5b7430596705c08b5ca8357",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":116,
              "y":480},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e193970ce67d424e906499d33ccfb06e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":116,
                  "y":480},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"450b2231bc5b4844b90ca0fde60cac73",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":642,
              "y":386},
            "size":{
              "width":118,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e55a1fb3acd54738bc90d4526913dc67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":642,
                  "y":386},
                "size":{
                  "width":118,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a6f0e0af7bd467aa2338f7377d13dd5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":624,
              "y":470},
            "size":{
              "width":524,
              "height":251},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86b1e01ae4ae4486b96b0eeb1ee59c45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":624,
                  "y":470},
                "size":{
                  "width":524,
                  "height":251},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页ok/u37.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c9e5fce28c6245e785a06b42b74654b2":{
      "scriptId":"u0"},
    "d7b345348d06412081bb774a265685d2":{
      "scriptId":"u1"},
    "7fc22ccc670c47b9a00e25ea512a43a0":{
      "scriptId":"u2"},
    "d156f962f72444b9bc6b6dc6c5cf3cf0":{
      "scriptId":"u3"},
    "ff035463188a4f4abd8a22bb1db33bb8":{
      "scriptId":"u4"},
    "9da4a964fea54056804552b95f5194fb":{
      "scriptId":"u5"},
    "5c8ca4c1a3544d4f86d1a89d57ff0f17":{
      "scriptId":"u6"},
    "d8da74b7ed7748da95120cffee2331cd":{
      "scriptId":"u7"},
    "a5a07e2f597143b4a2deeef9fa51f401":{
      "scriptId":"u8"},
    "51644cbcb417499d9979154f0c79210a":{
      "scriptId":"u9"},
    "f41a558b4a8541528b9702b29c287a22":{
      "scriptId":"u10"},
    "e9ffab0015d2431bb6d9febd65ab52c9":{
      "scriptId":"u11"},
    "2d0ed5cb90a44426a8cbeba5a5a9d14c":{
      "scriptId":"u12"},
    "adf1d25756294e28b30c955610a557d4":{
      "scriptId":"u13"},
    "85bfc87109134410ac3902ec222131fd":{
      "scriptId":"u14"},
    "b023da5bd35547048213aed01adc3624":{
      "scriptId":"u15"},
    "26a23776a4ae4e35a71930ff049ba4fd":{
      "scriptId":"u16"},
    "86181c1128e84caf82be480085ba3caf":{
      "scriptId":"u17"},
    "2952ef00517a404abdcb369a7f6dae7b":{
      "scriptId":"u18"},
    "778918e5b4774a87852dc3646e888a66":{
      "scriptId":"u19"},
    "57b830aebb3a43ba8467621ad225a89a":{
      "scriptId":"u20"},
    "cc00a64922ec473cbed831c209d524af":{
      "scriptId":"u21"},
    "4215e104dc944d838b5480af29c1d096":{
      "scriptId":"u22"},
    "f66f9342955e4405bcfec63fd4db3786":{
      "scriptId":"u23"},
    "fa470962eb4e4c9392169a4f18cf9fad":{
      "scriptId":"u24"},
    "ae18a5e724c049519faead8d458048f0":{
      "scriptId":"u25"},
    "84dcfc4b57084a6fa8e7cd208cee30b9":{
      "scriptId":"u26"},
    "677400aa52704a80aab463888d8b5d6d":{
      "scriptId":"u27"},
    "faec525d1d8647139f54ee7b9dc097be":{
      "scriptId":"u28"},
    "d31e612b72dd44b5b454e99e8cac349f":{
      "scriptId":"u29"},
    "40ad7a08971b42a881a58211fcc2cc3b":{
      "scriptId":"u30"},
    "8c4c0f14808c4d2b9e80c8e08f78d954":{
      "scriptId":"u31"},
    "166accc78c79416a9f2cb2c71cdda0d4":{
      "scriptId":"u32"},
    "02584fdca5b7430596705c08b5ca8357":{
      "scriptId":"u33"},
    "e193970ce67d424e906499d33ccfb06e":{
      "scriptId":"u34"},
    "450b2231bc5b4844b90ca0fde60cac73":{
      "scriptId":"u35"},
    "e55a1fb3acd54738bc90d4526913dc67":{
      "scriptId":"u36"},
    "4a6f0e0af7bd467aa2338f7377d13dd5":{
      "scriptId":"u37"},
    "86b1e01ae4ae4486b96b0eeb1ee59c45":{
      "scriptId":"u38"}}});