$axure.loadCurrentPage({
  "url":"启动页ok.html",
  "generationDate":new Date(1496627731439.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bae2d1842e924db4a8f5ba68aa3ce29a",
    "type":"Axure:Page",
    "name":"启动页ok",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c9e5fce28c6245e785a06b42b74654b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7b345348d06412081bb774a265685d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u1.png"}},
{
          "id":"7fc22ccc670c47b9a00e25ea512a43a0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d156f962f72444b9bc6b6dc6c5cf3cf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u3.png"}},
{
          "id":"ff035463188a4f4abd8a22bb1db33bb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":723},
            "size":{
              "width":481,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9da4a964fea54056804552b95f5194fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":723},
                "size":{
                  "width":481,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c8ca4c1a3544d4f86d1a89d57ff0f17",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":771},
            "size":{
              "width":190,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8da74b7ed7748da95120cffee2331cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":771},
                "size":{
                  "width":190,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5a07e2f597143b4a2deeef9fa51f401",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":131,
              "y":437},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51644cbcb417499d9979154f0c79210a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":131,
                  "y":437},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f41a558b4a8541528b9702b29c287a22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":124,
              "y":472},
            "size":{
              "width":131,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9ffab0015d2431bb6d9febd65ab52c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":124,
                  "y":472},
                "size":{
                  "width":131,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d0ed5cb90a44426a8cbeba5a5a9d14c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":88,
              "y":227},
            "size":{
              "width":200,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adf1d25756294e28b30c955610a557d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":88,
                  "y":227},
                "size":{
                  "width":200,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页ok/u12.png"}},
{
          "id":"43fd9afa42c643a0a485f012d66b6aaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":455,
              "y":0},
            "size":{
              "width":375,
              "height":667},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d0dc5908b1e4e5691433f643ca81c1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":455,
                  "y":0},
                "size":{
                  "width":375,
                  "height":667},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u1.png"}},
{
          "id":"1786bbd1b145442f924f018cd33df4de",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":455,
              "y":0},
            "size":{
              "width":375,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a68de362b2e14488a34dbbe7d3675cf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":455,
                  "y":0},
                "size":{
                  "width":375,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u3.png"}},
{
          "id":"682aecf195594262bc7412ec7d34e787",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":641,
              "y":574},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dccbd35fa0a418fb27b49268805bb8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":641,
                  "y":574},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d741d14149a453fb92f26c6c905071c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":574},
            "size":{
              "width":66,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f9b42571f8e4546a267b6ee464ed24e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":708,
                  "y":574},
                "size":{
                  "width":66,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2c2a5e781814fe2bd54de6e4b984d36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":455,
              "y":30},
            "size":{
              "width":375,
              "height":507},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ca7f4d4851f4bd8a855702f3f2c860e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":455,
                  "y":30},
                "size":{
                  "width":375,
                  "height":507},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页ok/u22.png"}},
{
          "id":"85bfc87109134410ac3902ec222131fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":880},
            "size":{
              "width":392,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b023da5bd35547048213aed01adc3624",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":880},
                "size":{
                  "width":392,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26a23776a4ae4e35a71930ff049ba4fd",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":227},
            "size":{
              "width":200,
              "height":200}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页(精选)ok",
                      "target":{
                        "targetType":"page",
                        "url":"首页_精选_ok.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"cf5cf117353a4064ab6822951922a18f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":582,
              "y":566},
            "size":{
              "width":51,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"260c5c73d0274c83ba95a0b46425e9a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":582,
                  "y":566},
                "size":{
                  "width":51,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页ok/u27.png"}},
{
          "id":"c2057c62d01a486db1f1faf85950adef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":40},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3ba59e10b974c9a910d7422d8d018af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":770,
                  "y":40},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页ok/u29.png"}},
{
          "id":"5184ea6e454645fd9b8e5df09fb1970b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":782,
              "y":57},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"993eada0173e4cc98eed45a5817db094",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":782,
                  "y":57},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36e00909530c4ee48f5af51ab7da436b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":896,
              "y":57},
            "size":{
              "width":184,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84d46ff7fab941d7bb74d7869c969582",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":896,
                  "y":57},
                "size":{
                  "width":184,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38b5e8e10a3146e4bc865c2ef991aa96",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":674,
              "y":282},
            "size":{
              "width":212,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/更新加载/u196_end.png",
            "line~":"images/启动页ok/u35_line.png"}},
{
          "id":"86ba32a0115849feb4d2b3b5c2e20ebb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "location":{
              "x":670,
              "y":284},
            "size":{
              "width":6,
              "height":6},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "cornerRadiusTopLeft":"3.5",
            "outerShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":3,
              "color":{
                "r":39,
                "g":162,
                "b":252,
                "a":0.447058823529412}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5fa763b32c548d28578e2481ec2ad31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "location":{
                  "x":670,
                  "y":284},
                "size":{
                  "width":6,
                  "height":6},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "cornerRadiusTopLeft":"3.5",
                "outerShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":3,
                  "color":{
                    "r":39,
                    "g":162,
                    "b":252,
                    "a":0.447058823529412}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u197.png"}},
{
          "id":"ac430e6c3bbd442bb56219a525c306a1",
          "label":"Header 2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":902,
              "y":267},
            "size":{
              "width":178,
              "height":40},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0680b72d7afa4e369d9f6e314c8c100b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":902,
                  "y":267},
                "size":{
                  "width":178,
                  "height":40},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62a314f94d064650b88fc83af9b01bde",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":811,
              "y":63},
            "size":{
              "width":75,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/更新加载/u196_end.png",
            "line~":"images/启动页ok/u40_line.png"}},
{
          "id":"5205f9e2653a4bb89769f31d5690e6c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "location":{
              "x":809,
              "y":65},
            "size":{
              "width":2,
              "height":6},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "cornerRadiusTopLeft":"3.5",
            "outerShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":3,
              "color":{
                "r":39,
                "g":162,
                "b":252,
                "a":0.447058823529412}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db22dd491bc94d6f9ca8dc84e3d24c14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "location":{
                  "x":809,
                  "y":65},
                "size":{
                  "width":2,
                  "height":6},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "cornerRadiusTopLeft":"3.5",
                "outerShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":3,
                  "color":{
                    "r":39,
                    "g":162,
                    "b":252,
                    "a":0.447058823529412}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页ok/u41.png"}},
{
          "id":"f673ebc9f6d0487d950c3ee00ae806e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1150,
              "y":0},
            "size":{
              "width":375,
              "height":667},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fda84f877c84db9bf2b1d17b6ddeed9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1150,
                  "y":0},
                "size":{
                  "width":375,
                  "height":667},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u1.png"}},
{
          "id":"b130e2ef6cc84d028edbc31b5ff35126",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1150,
              "y":0},
            "size":{
              "width":375,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efa3aa6f689e477d8c08cc791dc66151",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1150,
                  "y":0},
                "size":{
                  "width":375,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u3.png"}},
{
          "id":"89febe8ca30e4877a92f2fe60dd68cea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1158,
              "y":23},
            "size":{
              "width":22,
              "height":22},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63bf5baf6c39401383a15e98dd68e5e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1158,
                  "y":23},
                "size":{
                  "width":22,
                  "height":22},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页ok/u47.png"}},
{
          "id":"d50898e755454705bdf13242d1e15ad6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1150,
              "y":45},
            "size":{
              "width":375,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/启动页ok/u49_line.png"}},
{
          "id":"e326941fe6d741ea8895f939daced7ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1603,
              "y":25},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5598d8f6fdef4f238e73c14552472e08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1603,
                  "y":25},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2b6ab0e88204ca3a1f9ebc836c2b444",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1518,
              "y":29},
            "size":{
              "width":75,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/更新加载/u196_end.png",
            "line~":"images/启动页ok/u40_line.png"}},
{
          "id":"b8724a1d35a34e7ea0acd1564b5af1d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "location":{
              "x":1516,
              "y":31},
            "size":{
              "width":2,
              "height":6},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "cornerRadiusTopLeft":"3.5",
            "outerShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":3,
              "color":{
                "r":39,
                "g":162,
                "b":252,
                "a":0.447058823529412}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2498ae467514b9bbf028dfc9f604e92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "location":{
                  "x":1516,
                  "y":31},
                "size":{
                  "width":2,
                  "height":6},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "cornerRadiusTopLeft":"3.5",
                "outerShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":3,
                  "color":{
                    "r":39,
                    "g":162,
                    "b":252,
                    "a":0.447058823529412}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页ok/u41.png"}},
{
          "id":"ac65f5785c2440fe96e9541269930d0f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "opacity":"0.7",
            "location":{
              "x":1492,
              "y":22},
            "size":{
              "width":22,
              "height":22},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7e06d1ed9524783a0b8f41d7b6f06a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.7",
                "location":{
                  "x":1492,
                  "y":22},
                "size":{
                  "width":22,
                  "height":22},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页ok/u55.png"}},
{
          "id":"ec0495b39f684a62b99ef3730b6617a2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1080,
              "y":282},
            "size":{
              "width":212,
              "height":10},
            "rotation":"180",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/更新加载/u196_end.png",
            "line~":"images/启动页ok/u35_line.png"}},
{
          "id":"4d06ebd77e544583a215a0d8a27e4b6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "location":{
              "x":1290,
              "y":284},
            "size":{
              "width":6,
              "height":6},
            "rotation":"180",
            "textRotation":"180",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "cornerRadiusTopLeft":"3.5",
            "outerShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":3,
              "color":{
                "r":39,
                "g":162,
                "b":252,
                "a":0.447058823529412}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"982b973715354f60944dc15150c5a2ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "location":{
                  "x":1290,
                  "y":284},
                "size":{
                  "width":6,
                  "height":6},
                "rotation":"180",
                "textRotation":"180",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "cornerRadiusTopLeft":"3.5",
                "outerShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":3,
                  "color":{
                    "r":39,
                    "g":162,
                    "b":252,
                    "a":0.447058823529412}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u197.png"}},
{
          "id":"ae3e7b8b4fd0425980bc5518d2529562",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":316.5,
              "y":259.380889892578},
            "size":{
              "width":713,
              "height":10},
            "rotation":"45"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/启动页ok/u60_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c9e5fce28c6245e785a06b42b74654b2":{
      "scriptId":"u0"},
    "d7b345348d06412081bb774a265685d2":{
      "scriptId":"u1"},
    "7fc22ccc670c47b9a00e25ea512a43a0":{
      "scriptId":"u2"},
    "d156f962f72444b9bc6b6dc6c5cf3cf0":{
      "scriptId":"u3"},
    "ff035463188a4f4abd8a22bb1db33bb8":{
      "scriptId":"u4"},
    "9da4a964fea54056804552b95f5194fb":{
      "scriptId":"u5"},
    "5c8ca4c1a3544d4f86d1a89d57ff0f17":{
      "scriptId":"u6"},
    "d8da74b7ed7748da95120cffee2331cd":{
      "scriptId":"u7"},
    "a5a07e2f597143b4a2deeef9fa51f401":{
      "scriptId":"u8"},
    "51644cbcb417499d9979154f0c79210a":{
      "scriptId":"u9"},
    "f41a558b4a8541528b9702b29c287a22":{
      "scriptId":"u10"},
    "e9ffab0015d2431bb6d9febd65ab52c9":{
      "scriptId":"u11"},
    "2d0ed5cb90a44426a8cbeba5a5a9d14c":{
      "scriptId":"u12"},
    "adf1d25756294e28b30c955610a557d4":{
      "scriptId":"u13"},
    "43fd9afa42c643a0a485f012d66b6aaa":{
      "scriptId":"u14"},
    "9d0dc5908b1e4e5691433f643ca81c1f":{
      "scriptId":"u15"},
    "1786bbd1b145442f924f018cd33df4de":{
      "scriptId":"u16"},
    "a68de362b2e14488a34dbbe7d3675cf0":{
      "scriptId":"u17"},
    "682aecf195594262bc7412ec7d34e787":{
      "scriptId":"u18"},
    "5dccbd35fa0a418fb27b49268805bb8d":{
      "scriptId":"u19"},
    "0d741d14149a453fb92f26c6c905071c":{
      "scriptId":"u20"},
    "7f9b42571f8e4546a267b6ee464ed24e":{
      "scriptId":"u21"},
    "f2c2a5e781814fe2bd54de6e4b984d36":{
      "scriptId":"u22"},
    "6ca7f4d4851f4bd8a855702f3f2c860e":{
      "scriptId":"u23"},
    "85bfc87109134410ac3902ec222131fd":{
      "scriptId":"u24"},
    "b023da5bd35547048213aed01adc3624":{
      "scriptId":"u25"},
    "26a23776a4ae4e35a71930ff049ba4fd":{
      "scriptId":"u26"},
    "cf5cf117353a4064ab6822951922a18f":{
      "scriptId":"u27"},
    "260c5c73d0274c83ba95a0b46425e9a0":{
      "scriptId":"u28"},
    "c2057c62d01a486db1f1faf85950adef":{
      "scriptId":"u29"},
    "f3ba59e10b974c9a910d7422d8d018af":{
      "scriptId":"u30"},
    "5184ea6e454645fd9b8e5df09fb1970b":{
      "scriptId":"u31"},
    "993eada0173e4cc98eed45a5817db094":{
      "scriptId":"u32"},
    "36e00909530c4ee48f5af51ab7da436b":{
      "scriptId":"u33"},
    "84d46ff7fab941d7bb74d7869c969582":{
      "scriptId":"u34"},
    "38b5e8e10a3146e4bc865c2ef991aa96":{
      "scriptId":"u35"},
    "86ba32a0115849feb4d2b3b5c2e20ebb":{
      "scriptId":"u36"},
    "d5fa763b32c548d28578e2481ec2ad31":{
      "scriptId":"u37"},
    "ac430e6c3bbd442bb56219a525c306a1":{
      "scriptId":"u38"},
    "0680b72d7afa4e369d9f6e314c8c100b":{
      "scriptId":"u39"},
    "62a314f94d064650b88fc83af9b01bde":{
      "scriptId":"u40"},
    "5205f9e2653a4bb89769f31d5690e6c7":{
      "scriptId":"u41"},
    "db22dd491bc94d6f9ca8dc84e3d24c14":{
      "scriptId":"u42"},
    "f673ebc9f6d0487d950c3ee00ae806e2":{
      "scriptId":"u43"},
    "7fda84f877c84db9bf2b1d17b6ddeed9":{
      "scriptId":"u44"},
    "b130e2ef6cc84d028edbc31b5ff35126":{
      "scriptId":"u45"},
    "efa3aa6f689e477d8c08cc791dc66151":{
      "scriptId":"u46"},
    "89febe8ca30e4877a92f2fe60dd68cea":{
      "scriptId":"u47"},
    "63bf5baf6c39401383a15e98dd68e5e9":{
      "scriptId":"u48"},
    "d50898e755454705bdf13242d1e15ad6":{
      "scriptId":"u49"},
    "e326941fe6d741ea8895f939daced7ba":{
      "scriptId":"u50"},
    "5598d8f6fdef4f238e73c14552472e08":{
      "scriptId":"u51"},
    "d2b6ab0e88204ca3a1f9ebc836c2b444":{
      "scriptId":"u52"},
    "b8724a1d35a34e7ea0acd1564b5af1d4":{
      "scriptId":"u53"},
    "b2498ae467514b9bbf028dfc9f604e92":{
      "scriptId":"u54"},
    "ac65f5785c2440fe96e9541269930d0f":{
      "scriptId":"u55"},
    "d7e06d1ed9524783a0b8f41d7b6f06a0":{
      "scriptId":"u56"},
    "ec0495b39f684a62b99ef3730b6617a2":{
      "scriptId":"u57"},
    "4d06ebd77e544583a215a0d8a27e4b6a":{
      "scriptId":"u58"},
    "982b973715354f60944dc15150c5a2ef":{
      "scriptId":"u59"},
    "ae3e7b8b4fd0425980bc5518d2529562":{
      "scriptId":"u60"}}});