$axure.loadCurrentPage({
  "url":"举报ok.html",
  "generationDate":new Date(1497322453212.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5be8c6641ea5429ba51999b40673b4b4",
    "type":"Axure:Page",
    "name":"举报ok",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4a9e739825c3488b955d5c645846032e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"7eae0193a65e431ca4eb8ac17758a1d2"},
{
          "id":"71284a850e9345db87209ec39edab63e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":305,
              "y":538},
            "size":{
              "width":22,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"014f3d976bf64b5082a474443cd5afbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":305,
                  "y":538},
                "size":{
                  "width":22,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a54556869537485db2e4d95079e8dfcc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "opacity":"0.4",
            "location":{
              "x":282,
              "y":538},
            "size":{
              "width":18,
              "height":17},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9035a67fa8a4d6ca02bfd3c87ed0b16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.4",
                "location":{
                  "x":282,
                  "y":538},
                "size":{
                  "width":18,
                  "height":17},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u77.png"}},
{
          "id":"5955dc8b8bae419793811171f55fce44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "lineSpacing":"19px",
            "location":{
              "x":12,
              "y":574},
            "size":{
              "width":246,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fbfed1a4ce743fdb64d033deae8a6b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "lineSpacing":"19px",
                "location":{
                  "x":12,
                  "y":574},
                "size":{
                  "width":246,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d9914ba3c664663b59764c62adcb8cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFCFCFC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF0F0F0},
            "location":{
              "x":262,
              "y":574},
            "size":{
              "width":100,
              "height":49},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43c0bf8c5dcf4523b3db4a4c0de5dc43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFCFCFC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0F0F0},
                "location":{
                  "x":262,
                  "y":574},
                "size":{
                  "width":100,
                  "height":49},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索ok/u37.png"}},
{
          "id":"f6fb97832f05458a964634ea16f0da32",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":416},
            "size":{
              "width":374,
              "height":252},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"927a8acbff774f1fb3d0aa3472c98adf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":416},
                "size":{
                  "width":374,
                  "height":252},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索ok/u50.png"}},
{
          "id":"a6bc189a02d947b6908f61ba22a18aee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":0,
              "y":20},
            "size":{
              "width":375,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee10f716f5b7435ba3f4d31489ae9357",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":375,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/banner_____ok/u23.png"}},
{
          "id":"e05fa4e29dc3485caa664d53bbed1466",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":30},
            "size":{
              "width":22,
              "height":22},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdf7463bf1534ee5b97d1654dea0f3b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":30},
                "size":{
                  "width":22,
                  "height":22},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页ok/u47.png"}},
{
          "id":"cc460b82dfe2472cbbe24f55f46456dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":342,
              "y":30},
            "size":{
              "width":22,
              "height":22},
            "rotation":"90",
            "textRotation":"90",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e318804b4c5e4fd69aa1871e1b848016",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":342,
                  "y":30},
                "size":{
                  "width":22,
                  "height":22},
                "rotation":"90",
                "textRotation":"90",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/ta人文章详情_ok/u41.png"}},
{
          "id":"5c2933ece33f49998cb29f1ce3c1beba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xC9999999},
            "location":{
              "x":630,
              "y":704},
            "size":{
              "width":165,
              "height":130},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e98aefdbb9fe4c0e9160d4d33bcc8da3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xC9999999},
                "location":{
                  "x":630,
                  "y":704},
                "size":{
                  "width":165,
                  "height":130},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报ok/u39.png"}},
{
          "id":"54c8058548d540999387517139ceb897",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":686,
              "y":726},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"814b48275fa14d638840fb0965e2174d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":686,
                  "y":726},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报ok/u41.png"}},
{
          "id":"734d17a419824ee2a8bfe11eddf48f72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":687,
              "y":786},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cb2c9f7fce3425c9f0422443be8942d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":687,
                  "y":786},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59677592f4be43cebf74908d8b064f8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":55,
              "y":102},
            "size":{
              "width":270,
              "height":248},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59710203a5d14009b43200226b5af979",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":55,
                  "y":102},
                "size":{
                  "width":270,
                  "height":248},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报ok/u45.png"}},
{
          "id":"db0fea2ab80a4e588c64061dd1a7421a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":238},
            "size":{
              "width":208,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d44b825f3ebb48e79fc94507d366d996",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":238},
                "size":{
                  "width":208,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报ok/u47.png"}},
{
          "id":"e49a31b6e1be4c11b21f427bdc84e859",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":182},
            "size":{
              "width":143,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d8f098208ec4c9786b6c1e1f1f2e9e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":182},
                "size":{
                  "width":143,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0dd14d5a0b4542969745f3929f68d7cb",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":156},
            "size":{
              "width":130,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a2676ea7c36484faddbc9c93a607b78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":156},
                "size":{
                  "width":130,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"d7ba1c3b01b14e49bf955a6d446f9bdc",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":208},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c47ba0a15084a9cbff855952cc4b780",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":208},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e8541169b892456ca359d2c72651a8fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":143,
              "y":122},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e584fa70ca7f49c7a5f31c3ee0a7efad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":143,
                  "y":122},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"776ffe8094d247caaf640758e531e8ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":95,
              "y":244},
            "size":{
              "width":196,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c4fb8b0b82e4ef7ab06ac686f94b250",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":95,
                  "y":244},
                "size":{
                  "width":196,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e884a7258ea4595b84874ff652a5fc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":87,
              "y":312},
            "size":{
              "width":66,
              "height":26},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bfdb5cf62a543628ed3cf32ec85be8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":87,
                  "y":312},
                "size":{
                  "width":66,
                  "height":26},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报ok/u59.png"}},
{
          "id":"23d1fd7247454c76ba983b203448f97a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":229,
              "y":312},
            "size":{
              "width":66,
              "height":26},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e3dccef486c4086b69404bd2c17f110",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":229,
                  "y":312},
                "size":{
                  "width":66,
                  "height":26},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报ok/u59.png"}},
{
          "id":"91bc1e308ae746f4a0a6ee0498275e8a",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":704},
            "size":{
              "width":609,
              "height":246}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0702a61c324547109211ecee5523d121",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b434e6dce58f44e085efe2a8c4b3874a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/变更记录/u9.png"}},
{
              "id":"24adfdca2c604298b8ef58e4e7828e28",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":116},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"433e9d2f5e0046f68d2bf3030021881b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":116},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ta人文章详情_ok/u308.png"}},
{
              "id":"b220d7e9fda2485cb4ac7a6529424a97",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":372,
                  "y":0},
                "size":{
                  "width":119,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8b66093346994f23ac84d1e803d8904d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":372,
                      "y":0},
                    "size":{
                      "width":119,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ta人文章详情_ok/u184.png"}},
{
              "id":"d47740f24f0742a7b52c66a4929414d9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":30},
                "size":{
                  "width":119,
                  "height":116},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"67d2ae54da85466783b951e09367406f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":30},
                    "size":{
                      "width":119,
                      "height":116},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ta人文章详情_ok/u314.png"}},
{
              "id":"7b1e1a7e367b460484714b6f1bfc666e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":150,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ac33bde37c98473f8391f78aba4e2bac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ta人文章详情_ok/u180.png"}},
{
              "id":"73438279522a49b0a096966cc7c0e3da",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":150,
                  "height":116},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bad4d7cc02834f13a2dde74896d97ede",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":116},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ta人文章详情_ok/u310.png"}},
{
              "id":"cc436a9927fe4ba19e3ddfced975a563",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":491,
                  "y":0},
                "size":{
                  "width":118,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dc0dec46b7fa40a8b6330d9b91865e69",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":491,
                      "y":0},
                    "size":{
                      "width":118,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ta人文章详情_ok/u186.png"}},
{
              "id":"f830c0ed91dd4f39963b2f5bd80fb0bd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":491,
                  "y":30},
                "size":{
                  "width":118,
                  "height":116},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"31f85878b0be4ba58a3672edd158af09",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":491,
                      "y":30},
                    "size":{
                      "width":118,
                      "height":116},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/ta人文章详情_ok/u316.png"}},
{
              "id":"405bc37f3d864fb4a6a1cd64770dea09",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":250,
                  "y":0},
                "size":{
                  "width":122,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e50a4f3097864b149541e0c5dd8e1ad7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":250,
                      "y":0},
                    "size":{
                      "width":122,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/举报ok/u68.png"}},
{
              "id":"98bdcfdccaef42088274946809b6232f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":250,
                  "y":30},
                "size":{
                  "width":122,
                  "height":116},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7844d27f0b2f4769ab6f7bfcde582777",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":250,
                      "y":30},
                    "size":{
                      "width":122,
                      "height":116},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/举报ok/u78.png"}},
{
              "id":"21ba96266307457c9779bc7dc34ba45e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":146},
                "size":{
                  "width":100,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"81fc51e586764ff59011f0868d06b42b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":0,
                      "y":146},
                    "size":{
                      "width":100,
                      "height":100},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/无网页面ok/u41.png"}},
{
              "id":"11958ee220de400dbb85eafe0986e4a4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":146},
                "size":{
                  "width":150,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cecf08bf807746d6bdfa870acc1df2ca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":146},
                    "size":{
                      "width":150,
                      "height":100},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/举报ok/u86.png"}},
{
              "id":"e8345f8871da44a782e03da66b05bdc3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":250,
                  "y":146},
                "size":{
                  "width":122,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1de40ac739c848a5bf4120b890bb5e0f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":250,
                      "y":146},
                    "size":{
                      "width":122,
                      "height":100},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/举报ok/u88.png"}},
{
              "id":"188497a5336e476c84a52b0e2047bdf0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":372,
                  "y":146},
                "size":{
                  "width":119,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e7eed8320e8b4998a8d1b610cf6e019e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":372,
                      "y":146},
                    "size":{
                      "width":119,
                      "height":100},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/举报ok/u90.png"}},
{
              "id":"9f8f241c94d447f2a4ab81b5137d5408",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":491,
                  "y":146},
                "size":{
                  "width":118,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"efeeb2c6a2ce477d924bbe2dd0212c8e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":491,
                      "y":146},
                    "size":{
                      "width":118,
                      "height":100},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/举报ok/u92.png"}}]}]}},
  "masters":{
    "7eae0193a65e431ca4eb8ac17758a1d2":{
      "packageId":"7eae0193a65e431ca4eb8ac17758a1d2",
      "type":"Axure:Master",
      "name":"基础版",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"af226c488fc941e99484bd2cec4340b8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":375,
                "height":667},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8dd1e2ae969848c89b84fa587a460694",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":375,
                    "height":667},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u1.png"}},
{
            "id":"7284e38442fc45348b8cd88281ff40b3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":375,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8616946ea493495780d9b0b3611246e1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":375,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u3.png"}},
{
            "id":"d36da1d223a64946a9e94711eff4d1fd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF6F6F6},
              "location":{
                "x":1,
                "y":623},
              "size":{
                "width":375,
                "height":44},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d16164721be54e25b197dd7f375e03e6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF6F6F6},
                  "location":{
                    "x":1,
                    "y":623},
                  "size":{
                    "width":375,
                    "height":44},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u5.png"}},
{
            "id":"315f60303f144000ae765c6d624bf077",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":29,
                "y":628},
              "size":{
                "width":22,
                "height":23},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b24b94422e9e4efb87aec6e5adef1e28",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":29,
                    "y":628},
                  "size":{
                    "width":22,
                    "height":23},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u7.png"}},
{
            "id":"31a4ebba4b024c0985313097bd4aa241",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "opacity":"0.5",
              "location":{
                "x":128,
                "y":628},
              "size":{
                "width":22,
                "height":21},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"acd0c3901d5d492eb40e111abba88684",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.5",
                  "location":{
                    "x":128,
                    "y":628},
                  "size":{
                    "width":22,
                    "height":21},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u9.png"}},
{
            "id":"edba010e20634dc1ac330c3bf8d76748",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "opacity":"0.5",
              "location":{
                "x":325,
                "y":628},
              "size":{
                "width":22,
                "height":22},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a16f9a63e6624c72ae69bd642a87de50",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.5",
                  "location":{
                    "x":325,
                    "y":628},
                  "size":{
                    "width":22,
                    "height":22},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u11.png"}},
{
            "id":"c7807a3a08ad4fed9a38119bc20c8755",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "opacity":"0.5",
              "location":{
                "x":226,
                "y":628},
              "size":{
                "width":22,
                "height":22},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c26cef48b2564499bc5c30f85331e754",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.5",
                  "location":{
                    "x":226,
                    "y":628},
                  "size":{
                    "width":22,
                    "height":22},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u13.png"}},
{
            "id":"48809f0583444dcea10978992980261a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF868686,
                "opacity":1},
              "location":{
                "x":31,
                "y":652},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2378ba57c1274dd28ce75ae2102d4178",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF868686,
                    "opacity":1},
                  "location":{
                    "x":31,
                    "y":652},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5d3bac93c2934ccd9cdeaaf9db4428a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFBCBCBC,
                "opacity":1},
              "location":{
                "x":129,
                "y":652},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"314aac5cda1d4368ad98e59a8c422a75",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC,
                    "opacity":1},
                  "location":{
                    "x":129,
                    "y":652},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"262bd60e271747ee9a5adc99f7a3a2ef",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFBCBCBC,
                "opacity":1},
              "location":{
                "x":227,
                "y":652},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9a40c7bd14fe480ab352e3cea881e425",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC,
                    "opacity":1},
                  "location":{
                    "x":227,
                    "y":652},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"598eac4f5d6d41bba2fbab9208749178",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFBCBCBC,
                "opacity":1},
              "location":{
                "x":327,
                "y":652},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"99145e3a21ad4858a239c1698775eac9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC,
                    "opacity":1},
                  "location":{
                    "x":327,
                    "y":652},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "4a9e739825c3488b955d5c645846032e":{
      "scriptId":"u0",
      "af226c488fc941e99484bd2cec4340b8":{
        "scriptId":"u1"},
      "8dd1e2ae969848c89b84fa587a460694":{
        "scriptId":"u2"},
      "7284e38442fc45348b8cd88281ff40b3":{
        "scriptId":"u3"},
      "8616946ea493495780d9b0b3611246e1":{
        "scriptId":"u4"},
      "d36da1d223a64946a9e94711eff4d1fd":{
        "scriptId":"u5"},
      "d16164721be54e25b197dd7f375e03e6":{
        "scriptId":"u6"},
      "315f60303f144000ae765c6d624bf077":{
        "scriptId":"u7"},
      "b24b94422e9e4efb87aec6e5adef1e28":{
        "scriptId":"u8"},
      "31a4ebba4b024c0985313097bd4aa241":{
        "scriptId":"u9"},
      "acd0c3901d5d492eb40e111abba88684":{
        "scriptId":"u10"},
      "edba010e20634dc1ac330c3bf8d76748":{
        "scriptId":"u11"},
      "a16f9a63e6624c72ae69bd642a87de50":{
        "scriptId":"u12"},
      "c7807a3a08ad4fed9a38119bc20c8755":{
        "scriptId":"u13"},
      "c26cef48b2564499bc5c30f85331e754":{
        "scriptId":"u14"},
      "48809f0583444dcea10978992980261a":{
        "scriptId":"u15"},
      "2378ba57c1274dd28ce75ae2102d4178":{
        "scriptId":"u16"},
      "5d3bac93c2934ccd9cdeaaf9db4428a6":{
        "scriptId":"u17"},
      "314aac5cda1d4368ad98e59a8c422a75":{
        "scriptId":"u18"},
      "262bd60e271747ee9a5adc99f7a3a2ef":{
        "scriptId":"u19"},
      "9a40c7bd14fe480ab352e3cea881e425":{
        "scriptId":"u20"},
      "598eac4f5d6d41bba2fbab9208749178":{
        "scriptId":"u21"},
      "99145e3a21ad4858a239c1698775eac9":{
        "scriptId":"u22"}},
    "71284a850e9345db87209ec39edab63e":{
      "scriptId":"u23"},
    "014f3d976bf64b5082a474443cd5afbf":{
      "scriptId":"u24"},
    "a54556869537485db2e4d95079e8dfcc":{
      "scriptId":"u25"},
    "d9035a67fa8a4d6ca02bfd3c87ed0b16":{
      "scriptId":"u26"},
    "5955dc8b8bae419793811171f55fce44":{
      "scriptId":"u27"},
    "1fbfed1a4ce743fdb64d033deae8a6b9":{
      "scriptId":"u28"},
    "6d9914ba3c664663b59764c62adcb8cc":{
      "scriptId":"u29"},
    "43c0bf8c5dcf4523b3db4a4c0de5dc43":{
      "scriptId":"u30"},
    "f6fb97832f05458a964634ea16f0da32":{
      "scriptId":"u31"},
    "927a8acbff774f1fb3d0aa3472c98adf":{
      "scriptId":"u32"},
    "a6bc189a02d947b6908f61ba22a18aee":{
      "scriptId":"u33"},
    "ee10f716f5b7435ba3f4d31489ae9357":{
      "scriptId":"u34"},
    "e05fa4e29dc3485caa664d53bbed1466":{
      "scriptId":"u35"},
    "bdf7463bf1534ee5b97d1654dea0f3b1":{
      "scriptId":"u36"},
    "cc460b82dfe2472cbbe24f55f46456dd":{
      "scriptId":"u37"},
    "e318804b4c5e4fd69aa1871e1b848016":{
      "scriptId":"u38"},
    "5c2933ece33f49998cb29f1ce3c1beba":{
      "scriptId":"u39"},
    "e98aefdbb9fe4c0e9160d4d33bcc8da3":{
      "scriptId":"u40"},
    "54c8058548d540999387517139ceb897":{
      "scriptId":"u41"},
    "814b48275fa14d638840fb0965e2174d":{
      "scriptId":"u42"},
    "734d17a419824ee2a8bfe11eddf48f72":{
      "scriptId":"u43"},
    "7cb2c9f7fce3425c9f0422443be8942d":{
      "scriptId":"u44"},
    "59677592f4be43cebf74908d8b064f8c":{
      "scriptId":"u45"},
    "59710203a5d14009b43200226b5af979":{
      "scriptId":"u46"},
    "db0fea2ab80a4e588c64061dd1a7421a":{
      "scriptId":"u47"},
    "d44b825f3ebb48e79fc94507d366d996":{
      "scriptId":"u48"},
    "e49a31b6e1be4c11b21f427bdc84e859":{
      "scriptId":"u49"},
    "0d8f098208ec4c9786b6c1e1f1f2e9e6":{
      "scriptId":"u50"},
    "0dd14d5a0b4542969745f3929f68d7cb":{
      "scriptId":"u51"},
    "4a2676ea7c36484faddbc9c93a607b78":{
      "scriptId":"u52"},
    "d7ba1c3b01b14e49bf955a6d446f9bdc":{
      "scriptId":"u53"},
    "6c47ba0a15084a9cbff855952cc4b780":{
      "scriptId":"u54"},
    "e8541169b892456ca359d2c72651a8fa":{
      "scriptId":"u55"},
    "e584fa70ca7f49c7a5f31c3ee0a7efad":{
      "scriptId":"u56"},
    "776ffe8094d247caaf640758e531e8ac":{
      "scriptId":"u57"},
    "2c4fb8b0b82e4ef7ab06ac686f94b250":{
      "scriptId":"u58"},
    "9e884a7258ea4595b84874ff652a5fc9":{
      "scriptId":"u59"},
    "8bfdb5cf62a543628ed3cf32ec85be8d":{
      "scriptId":"u60"},
    "23d1fd7247454c76ba983b203448f97a":{
      "scriptId":"u61"},
    "3e3dccef486c4086b69404bd2c17f110":{
      "scriptId":"u62"},
    "91bc1e308ae746f4a0a6ee0498275e8a":{
      "scriptId":"u63"},
    "0702a61c324547109211ecee5523d121":{
      "scriptId":"u64"},
    "b434e6dce58f44e085efe2a8c4b3874a":{
      "scriptId":"u65"},
    "7b1e1a7e367b460484714b6f1bfc666e":{
      "scriptId":"u66"},
    "ac33bde37c98473f8391f78aba4e2bac":{
      "scriptId":"u67"},
    "405bc37f3d864fb4a6a1cd64770dea09":{
      "scriptId":"u68"},
    "e50a4f3097864b149541e0c5dd8e1ad7":{
      "scriptId":"u69"},
    "b220d7e9fda2485cb4ac7a6529424a97":{
      "scriptId":"u70"},
    "8b66093346994f23ac84d1e803d8904d":{
      "scriptId":"u71"},
    "cc436a9927fe4ba19e3ddfced975a563":{
      "scriptId":"u72"},
    "dc0dec46b7fa40a8b6330d9b91865e69":{
      "scriptId":"u73"},
    "24adfdca2c604298b8ef58e4e7828e28":{
      "scriptId":"u74"},
    "433e9d2f5e0046f68d2bf3030021881b":{
      "scriptId":"u75"},
    "73438279522a49b0a096966cc7c0e3da":{
      "scriptId":"u76"},
    "bad4d7cc02834f13a2dde74896d97ede":{
      "scriptId":"u77"},
    "98bdcfdccaef42088274946809b6232f":{
      "scriptId":"u78"},
    "7844d27f0b2f4769ab6f7bfcde582777":{
      "scriptId":"u79"},
    "d47740f24f0742a7b52c66a4929414d9":{
      "scriptId":"u80"},
    "67d2ae54da85466783b951e09367406f":{
      "scriptId":"u81"},
    "f830c0ed91dd4f39963b2f5bd80fb0bd":{
      "scriptId":"u82"},
    "31f85878b0be4ba58a3672edd158af09":{
      "scriptId":"u83"},
    "21ba96266307457c9779bc7dc34ba45e":{
      "scriptId":"u84"},
    "81fc51e586764ff59011f0868d06b42b":{
      "scriptId":"u85"},
    "11958ee220de400dbb85eafe0986e4a4":{
      "scriptId":"u86"},
    "cecf08bf807746d6bdfa870acc1df2ca":{
      "scriptId":"u87"},
    "e8345f8871da44a782e03da66b05bdc3":{
      "scriptId":"u88"},
    "1de40ac739c848a5bf4120b890bb5e0f":{
      "scriptId":"u89"},
    "188497a5336e476c84a52b0e2047bdf0":{
      "scriptId":"u90"},
    "e7eed8320e8b4998a8d1b610cf6e019e":{
      "scriptId":"u91"},
    "9f8f241c94d447f2a4ab81b5137d5408":{
      "scriptId":"u92"},
    "efeeb2c6a2ce477d924bbe2dd0212c8e":{
      "scriptId":"u93"}}});