$axure.loadCurrentPage({
  "url":"未登陆_ok.html",
  "generationDate":new Date(1500893914012.59),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9d1967fc7c2e4d4ca3ae7ebcf0ce4830",
    "type":"Axure:Page",
    "name":"未登陆 OK",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e1337578722c4873876294a3ddbbf461",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"7eae0193a65e431ca4eb8ac17758a1d2"},
{
          "id":"e6ca609fa36044328ee38a48573eafba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":47,
              "y":68},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8e77561ac6741128ad6f65560db78fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":47,
                  "y":68},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0532f5a12504b66b1203b721498a754",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":298,
              "y":68},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ab1012741b9482ea6e3facd1610f8b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":298,
                  "y":68},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a4865a5c1a7463981f8c13f071a31e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":173,
              "y":68},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b335ecc154e46abac3d32e7798e21e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":173,
                  "y":68},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44f72e79dc274e738f9e3da21bd5d631",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":298,
              "y":84},
            "size":{
              "width":29,
              "height":10},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/更新加载/u35_line.png"}},
{
          "id":"6369d60394d74335bce526ac4d1a51a1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":109,
              "y":71},
            "size":{
              "width":17,
              "height":10},
            "rotation":"90",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/更新加载/u36_line.png"}},
{
          "id":"8bd9b4830ac14e3493810602f8fd0991",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":71},
            "size":{
              "width":17,
              "height":10},
            "rotation":"90",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/更新加载/u36_line.png"}},
{
          "id":"602cf3cc392b4e909efe1c588136d91d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":89},
            "size":{
              "width":358,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/关注_ok/u32_line.png"}},
{
          "id":"3ae4567bcc3540779857edd3a2f92b65",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":149,
              "y":314},
            "size":{
              "width":73,
              "height":26},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4dd0aa1c15e4bd082d57bba2a30cde9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":149,
                  "y":314},
                "size":{
                  "width":73,
                  "height":26},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索ok/u596.png"}},
{
          "id":"99ba6b168e4248e0b0ebd2b985141007",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":39,
              "y":265},
            "size":{
              "width":306,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c49d849ee8504a7d866a03f99233b6fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":39,
                  "y":265},
                "size":{
                  "width":306,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"524093bb3def4897b6d87d022fc4d1fd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":664},
            "size":{
              "width":350,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/更新加载/u40_line.png"}},
{
          "id":"55006fdba5e14494831667b5d515c860",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":23},
            "size":{
              "width":320,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"31"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26588eccb7264046b4c712bc8b5cc53d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":23},
                "size":{
                  "width":320,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"31"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u23.png"}},
{
          "id":"ace325d2a369466eaaa38b174121dd13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":176,
              "y":29},
            "size":{
              "width":25,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37f28d85f9134eb5af2f7d72bb5b3403",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":176,
                  "y":29},
                "size":{
                  "width":25,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3c60fb6ff9748c6a09df8015d6bc5f9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "location":{
              "x":43,
              "y":29},
            "size":{
              "width":16,
              "height":16},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39759e7402c149c4adc99444f2b14bed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "location":{
                  "x":43,
                  "y":29},
                "size":{
                  "width":16,
                  "height":16},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u33.png"}},
{
          "id":"90c80af5369548238c2d1fc3e33c8190",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":49},
            "size":{
              "width":373,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/更新加载/u81_line.png"}}]}},
  "masters":{
    "7eae0193a65e431ca4eb8ac17758a1d2":{
      "packageId":"7eae0193a65e431ca4eb8ac17758a1d2",
      "type":"Axure:Master",
      "name":"基础版",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"af226c488fc941e99484bd2cec4340b8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":375,
                "height":667},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8dd1e2ae969848c89b84fa587a460694",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":375,
                    "height":667},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u1.png"}},
{
            "id":"7284e38442fc45348b8cd88281ff40b3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":375,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8616946ea493495780d9b0b3611246e1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":375,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u3.png"}},
{
            "id":"d36da1d223a64946a9e94711eff4d1fd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF6F6F6},
              "location":{
                "x":1,
                "y":623},
              "size":{
                "width":375,
                "height":44},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d16164721be54e25b197dd7f375e03e6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF6F6F6},
                  "location":{
                    "x":1,
                    "y":623},
                  "size":{
                    "width":375,
                    "height":44},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u5.png"}},
{
            "id":"315f60303f144000ae765c6d624bf077",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":29,
                "y":628},
              "size":{
                "width":22,
                "height":23},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b24b94422e9e4efb87aec6e5adef1e28",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":29,
                    "y":628},
                  "size":{
                    "width":22,
                    "height":23},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u7.png"}},
{
            "id":"31a4ebba4b024c0985313097bd4aa241",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "opacity":"0.5",
              "location":{
                "x":128,
                "y":628},
              "size":{
                "width":22,
                "height":21},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"acd0c3901d5d492eb40e111abba88684",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.5",
                  "location":{
                    "x":128,
                    "y":628},
                  "size":{
                    "width":22,
                    "height":21},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u9.png"}},
{
            "id":"edba010e20634dc1ac330c3bf8d76748",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "opacity":"0.5",
              "location":{
                "x":325,
                "y":628},
              "size":{
                "width":22,
                "height":22},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a16f9a63e6624c72ae69bd642a87de50",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.5",
                  "location":{
                    "x":325,
                    "y":628},
                  "size":{
                    "width":22,
                    "height":22},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u11.png"}},
{
            "id":"c7807a3a08ad4fed9a38119bc20c8755",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "opacity":"0.5",
              "location":{
                "x":226,
                "y":628},
              "size":{
                "width":22,
                "height":22},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c26cef48b2564499bc5c30f85331e754",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.5",
                  "location":{
                    "x":226,
                    "y":628},
                  "size":{
                    "width":22,
                    "height":22},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u13.png"}},
{
            "id":"48809f0583444dcea10978992980261a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF868686,
                "opacity":1},
              "location":{
                "x":31,
                "y":652},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2378ba57c1274dd28ce75ae2102d4178",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF868686,
                    "opacity":1},
                  "location":{
                    "x":31,
                    "y":652},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5d3bac93c2934ccd9cdeaaf9db4428a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFBCBCBC,
                "opacity":1},
              "location":{
                "x":129,
                "y":652},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"314aac5cda1d4368ad98e59a8c422a75",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC,
                    "opacity":1},
                  "location":{
                    "x":129,
                    "y":652},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"262bd60e271747ee9a5adc99f7a3a2ef",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFBCBCBC,
                "opacity":1},
              "location":{
                "x":227,
                "y":652},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9a40c7bd14fe480ab352e3cea881e425",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC,
                    "opacity":1},
                  "location":{
                    "x":227,
                    "y":652},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"598eac4f5d6d41bba2fbab9208749178",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFBCBCBC,
                "opacity":1},
              "location":{
                "x":327,
                "y":652},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"99145e3a21ad4858a239c1698775eac9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC,
                    "opacity":1},
                  "location":{
                    "x":327,
                    "y":652},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "e1337578722c4873876294a3ddbbf461":{
      "scriptId":"u0",
      "af226c488fc941e99484bd2cec4340b8":{
        "scriptId":"u1"},
      "8dd1e2ae969848c89b84fa587a460694":{
        "scriptId":"u2"},
      "7284e38442fc45348b8cd88281ff40b3":{
        "scriptId":"u3"},
      "8616946ea493495780d9b0b3611246e1":{
        "scriptId":"u4"},
      "d36da1d223a64946a9e94711eff4d1fd":{
        "scriptId":"u5"},
      "d16164721be54e25b197dd7f375e03e6":{
        "scriptId":"u6"},
      "315f60303f144000ae765c6d624bf077":{
        "scriptId":"u7"},
      "b24b94422e9e4efb87aec6e5adef1e28":{
        "scriptId":"u8"},
      "31a4ebba4b024c0985313097bd4aa241":{
        "scriptId":"u9"},
      "acd0c3901d5d492eb40e111abba88684":{
        "scriptId":"u10"},
      "edba010e20634dc1ac330c3bf8d76748":{
        "scriptId":"u11"},
      "a16f9a63e6624c72ae69bd642a87de50":{
        "scriptId":"u12"},
      "c7807a3a08ad4fed9a38119bc20c8755":{
        "scriptId":"u13"},
      "c26cef48b2564499bc5c30f85331e754":{
        "scriptId":"u14"},
      "48809f0583444dcea10978992980261a":{
        "scriptId":"u15"},
      "2378ba57c1274dd28ce75ae2102d4178":{
        "scriptId":"u16"},
      "5d3bac93c2934ccd9cdeaaf9db4428a6":{
        "scriptId":"u17"},
      "314aac5cda1d4368ad98e59a8c422a75":{
        "scriptId":"u18"},
      "262bd60e271747ee9a5adc99f7a3a2ef":{
        "scriptId":"u19"},
      "9a40c7bd14fe480ab352e3cea881e425":{
        "scriptId":"u20"},
      "598eac4f5d6d41bba2fbab9208749178":{
        "scriptId":"u21"},
      "99145e3a21ad4858a239c1698775eac9":{
        "scriptId":"u22"}},
    "e6ca609fa36044328ee38a48573eafba":{
      "scriptId":"u23"},
    "d8e77561ac6741128ad6f65560db78fa":{
      "scriptId":"u24"},
    "f0532f5a12504b66b1203b721498a754":{
      "scriptId":"u25"},
    "9ab1012741b9482ea6e3facd1610f8b3":{
      "scriptId":"u26"},
    "3a4865a5c1a7463981f8c13f071a31e6":{
      "scriptId":"u27"},
    "1b335ecc154e46abac3d32e7798e21e7":{
      "scriptId":"u28"},
    "44f72e79dc274e738f9e3da21bd5d631":{
      "scriptId":"u29"},
    "6369d60394d74335bce526ac4d1a51a1":{
      "scriptId":"u30"},
    "8bd9b4830ac14e3493810602f8fd0991":{
      "scriptId":"u31"},
    "602cf3cc392b4e909efe1c588136d91d":{
      "scriptId":"u32"},
    "3ae4567bcc3540779857edd3a2f92b65":{
      "scriptId":"u33"},
    "f4dd0aa1c15e4bd082d57bba2a30cde9":{
      "scriptId":"u34"},
    "99ba6b168e4248e0b0ebd2b985141007":{
      "scriptId":"u35"},
    "c49d849ee8504a7d866a03f99233b6fd":{
      "scriptId":"u36"},
    "524093bb3def4897b6d87d022fc4d1fd":{
      "scriptId":"u37"},
    "55006fdba5e14494831667b5d515c860":{
      "scriptId":"u38"},
    "26588eccb7264046b4c712bc8b5cc53d":{
      "scriptId":"u39"},
    "ace325d2a369466eaaa38b174121dd13":{
      "scriptId":"u40"},
    "37f28d85f9134eb5af2f7d72bb5b3403":{
      "scriptId":"u41"},
    "f3c60fb6ff9748c6a09df8015d6bc5f9":{
      "scriptId":"u42"},
    "39759e7402c149c4adc99444f2b14bed":{
      "scriptId":"u43"},
    "90c80af5369548238c2d1fc3e33c8190":{
      "scriptId":"u44"}}});