$axure.loadCurrentPage({
  "url":"评论详情ok.html",
  "generationDate":new Date(1496627738408.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"42000857b043497e9255254809d4689a",
    "type":"Axure:Page",
    "name":"评论详情ok",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4b03b57a7a9f42dda127d245b648e6cd",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"7eae0193a65e431ca4eb8ac17758a1d2"},
{
          "id":"f005539e1928407592faa3ae055f470f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":7,
              "y":70},
            "size":{
              "width":26,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f85f86fbbb749ecbb48302d24ea8c9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":7,
                  "y":70},
                "size":{
                  "width":26,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/ta人文章详情_ok/u27.png"}},
{
          "id":"5f8ef7e07f284ef290683779bc674bf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":74},
            "size":{
              "width":105,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da6087a31dbc4a50af58452226d87a86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":74},
                "size":{
                  "width":105,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4770b93d568443dc8322b5c7506686f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":113},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d08b807276974f83a320ced141947269",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":113},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad6ec22f3d974503bba873d04966ccff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":41,
              "y":90},
            "size":{
              "width":29,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5447f56dd9834d07aa13816ed90fecf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":41,
                  "y":90},
                "size":{
                  "width":29,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3ebcb745b1f49d48469052798a7d391",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":240},
            "size":{
              "width":316,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1361a0cadfdd43069b51b794ab55f5bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":240},
                "size":{
                  "width":316,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b1a16b92d1b4531b2efccc75acb624e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":7,
              "y":282},
            "size":{
              "width":361,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/ta人文章详情_ok/u102_line.png"}},
{
          "id":"8fc3942174c8441ebec27858717e06fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":161,
              "y":296},
            "size":{
              "width":19,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ae217ca2a6b4e28922a750a20ce6d38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":161,
                  "y":296},
                "size":{
                  "width":19,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e609fb2825e04e9c94ea20102f29438f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":626},
            "size":{
              "width":375,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f2ad39e24dd488b941f8b4cc839d3af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":626},
                "size":{
                  "width":375,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/ta人文章详情_ok/u79.png"}},
{
          "id":"226aefea9cd141d183fb72d8a611fb4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":632},
            "size":{
              "width":351,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c96d6d2bfc94f95a3102d1296bd2b91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":12,
                  "y":632},
                "size":{
                  "width":351,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评论详情ok/u38.png"}},
{
          "id":"3438403bf87a49f69f8bfca94e8ef08c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":48,
              "y":639},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8143b4cffa584e1280d7a07a311d0174",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":48,
                  "y":639},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd75d40e248d40da99c0e998bbe79fc2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":636},
            "size":{
              "width":22,
              "height":22},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b35e2a25307427e9cb023ba13d7d162",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":636},
                "size":{
                  "width":22,
                  "height":22},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/ta人文章详情_ok/u87.png"}},
{
          "id":"e5d53c15b09c4f53ab0d2388a055215a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF6F6F6},
            "location":{
              "x":1,
              "y":19},
            "size":{
              "width":375,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6247a7ecb6924e9186dc70311c6d4824",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF6F6F6},
                "location":{
                  "x":1,
                  "y":19},
                "size":{
                  "width":375,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/banner_____ok/u23.png"}},
{
          "id":"31cc37b176f04f82ac963e99490f82d6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":28},
            "size":{
              "width":22,
              "height":22},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"897baf60476d483386890c70bdbbe8ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":28},
                "size":{
                  "width":22,
                  "height":22},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动页ok/u47.png"}},
{
          "id":"4fa1457cdf964ae397bd40f992669048",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":37},
            "size":{
              "width":477,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/更新加载/u196_end.png",
            "line~":"images/ta人文章详情_ok/u138_line.png"}},
{
          "id":"93bd56b59494432ebe328a454067a7b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "location":{
              "x":18,
              "y":39},
            "size":{
              "width":6,
              "height":6},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "cornerRadiusTopLeft":"3.5",
            "outerShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":3,
              "color":{
                "r":39,
                "g":162,
                "b":252,
                "a":0.447058823529412}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"557de1f6e4b04674b0cb67c565655694",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "location":{
                  "x":18,
                  "y":39},
                "size":{
                  "width":6,
                  "height":6},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "cornerRadiusTopLeft":"3.5",
                "outerShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":3,
                  "color":{
                    "r":39,
                    "g":162,
                    "b":252,
                    "a":0.447058823529412}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u197.png"}},
{
          "id":"2f81365fb6744932a9d6f50fef491e56",
          "label":"Header 2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":509,
              "y":32},
            "size":{
              "width":127,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31b7b26774084a89a13fcc28b91cb511",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":509,
                  "y":32},
                "size":{
                  "width":127,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58c94dc28b844092ac7e5a2aeeea6833",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":86},
            "size":{
              "width":473,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/更新加载/u196_end.png",
            "line~":"images/评论详情ok/u53_line.png"}},
{
          "id":"706e9f46bc6b453d8e7030c4caf27bb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "location":{
              "x":22,
              "y":88},
            "size":{
              "width":6,
              "height":6},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "cornerRadiusTopLeft":"3.5",
            "outerShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":3,
              "color":{
                "r":39,
                "g":162,
                "b":252,
                "a":0.447058823529412}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae0805d3cd0143c2a8d20f14fadfa11d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "location":{
                  "x":22,
                  "y":88},
                "size":{
                  "width":6,
                  "height":6},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "cornerRadiusTopLeft":"3.5",
                "outerShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":3,
                  "color":{
                    "r":39,
                    "g":162,
                    "b":252,
                    "a":0.447058823529412}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u197.png"}},
{
          "id":"79348dec5fb04dd494cdfd72d0811c1d",
          "label":"Header 2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":509,
              "y":81},
            "size":{
              "width":225,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db948b29d73e4d608c05f0d35ea2d212",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":509,
                  "y":81},
                "size":{
                  "width":225,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48ac85e3d38c44eba333e98fddea60fa",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":123,
              "y":116},
            "size":{
              "width":376,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/更新加载/u196_end.png",
            "line~":"images/评论详情ok/u58_line.png"}},
{
          "id":"229b5f6351db46d28bd60cc96e66c882",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "location":{
              "x":119,
              "y":118},
            "size":{
              "width":6,
              "height":6},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "cornerRadiusTopLeft":"3.5",
            "outerShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":3,
              "color":{
                "r":39,
                "g":162,
                "b":252,
                "a":0.447058823529412}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e8b95e5c68e4892b4bec7220d5204cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "location":{
                  "x":119,
                  "y":118},
                "size":{
                  "width":6,
                  "height":6},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "cornerRadiusTopLeft":"3.5",
                "outerShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":3,
                  "color":{
                    "r":39,
                    "g":162,
                    "b":252,
                    "a":0.447058823529412}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/更新加载/u197.png"}},
{
          "id":"65b4a8d55420437788934f73bcfaf644",
          "label":"Header 2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":509,
              "y":111},
            "size":{
              "width":309,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a8002fe6cb644c79a12cdfa3bfe17d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":509,
                  "y":111},
                "size":{
                  "width":309,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3aa65b47f5a64faaa9e17f3e8e451fde",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":141},
            "size":{
              "width":90,
              "height":59},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41b6251bf3d04f55af17ccd93bd7ed80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":141},
                "size":{
                  "width":90,
                  "height":59},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评论详情ok/u63.png"}},
{
          "id":"6791a0ee21b24030a8ee41e073cc7a0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":178},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"914c58222f124d46b4bf5e67ac5e1838",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":178},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fb6e178647d4e9ba390a5ef72f9729a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":576,
              "y":178},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ba043a80394479196860b5d8bad7639",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":576,
                  "y":178},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a1e9d79497448dd808c97e66302fa77",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":530,
              "y":148},
            "size":{
              "width":26,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be37bde4fc1644aca537244a5ececd96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":530,
                  "y":148},
                "size":{
                  "width":26,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/ta人文章详情_ok/u27.png"}},
{
          "id":"d33869c7e8d1460ca560d967402501ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":576.5,
              "y":148},
            "size":{
              "width":26,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9a01abad50c44d08b4248838b4fe8ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":576.5,
                  "y":148},
                "size":{
                  "width":26,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/ta人文章详情_ok/u27.png"}},
{
          "id":"9b7942e6b4b5446d8bfcef5d5daa7c0a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":209},
            "size":{
              "width":359,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/更新加载/u196_end.png",
            "line~":"images/评论详情ok/u73_line.png"}},
{
          "id":"11cb4394cfb34cd7a61a443dc4b8d8a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "location":{
              "x":137,
              "y":211},
            "size":{
              "width":5,
              "height":6},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7AC6FE},
            "cornerRadiusTopLeft":"3.5",
            "outerShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":3,
              "color":{
                "r":39,
                "g":162,
                "b":252,
                "a":0.447058823529412}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7437761a13ae4b848e034c5d8afb9930",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "location":{
                  "x":137,
                  "y":211},
                "size":{
                  "width":5,
                  "height":6},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF7AC6FE},
                "cornerRadiusTopLeft":"3.5",
                "outerShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":3,
                  "color":{
                    "r":39,
                    "g":162,
                    "b":252,
                    "a":0.447058823529412}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评论详情ok/u74.png"}},
{
          "id":"713a6bdea23740d0a430a53a3b6766fb",
          "label":"Header 2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":509,
              "y":204},
            "size":{
              "width":183,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"853f8226f917411a8e0e1548b30f7363",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":509,
                  "y":204},
                "size":{
                  "width":183,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6fe14d937854f4faece9fc7864a44d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":156},
            "size":{
              "width":316,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0712a8dc6dd4960afdc3eae755f6f96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":156},
                "size":{
                  "width":316,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4119579a9650414db4e13a89a6ed4c90",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":198},
            "size":{
              "width":316,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"087428765d2d478f8a59fcdaba0d8816",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":198},
                "size":{
                  "width":316,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34cf9674bcc64440b139c968c4c6ccf4",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":559,
              "y":141},
            "size":{
              "width":10,
              "height":59},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/评论详情ok/u82_line.png"}},
{
          "id":"aeccd8aca7e84eec82470216cb1c182f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":868,
              "y":141},
            "size":{
              "width":209,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"511ce5420c634b8da4bd9c4162dd60f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":868,
                  "y":141},
                "size":{
                  "width":209,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b0d842ed8f1429abc85680ef283a0ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":328,
              "y":173},
            "size":{
              "width":29,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca9ec6b54be342b9b4de3293290d824e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":328,
                  "y":173},
                "size":{
                  "width":29,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d50de8a9b2ef406b88c5f809cd963377",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":328,
              "y":215},
            "size":{
              "width":29,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ab4c9fca1744211a111bcd0cff8549b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":328,
                  "y":215},
                "size":{
                  "width":29,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5458bb72ffc42fea15f1dd880c31b98",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":328,
              "y":257},
            "size":{
              "width":29,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abd487c69a044af7a239993ee971a837",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":328,
                  "y":257},
                "size":{
                  "width":29,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22db26de4ee5458fb57f19cf30396f12",
          "label":"Header 2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":509,
              "y":224},
            "size":{
              "width":169,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c80bb6b72a464d648ddd64cd87a90de5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":509,
                  "y":224},
                "size":{
                  "width":169,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6500b2737d844620aba2960444c9527a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":141},
            "size":{
              "width":98,
              "height":59},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64b167fa7baa44aa833457a88dc3ee78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":760,
                  "y":141},
                "size":{
                  "width":98,
                  "height":59},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评论详情ok/u93.png"}},
{
          "id":"cd69bee435e14b02a9017b57236fbc4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":178},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4425e5d73635429a900499702abc94b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":770,
                  "y":178},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"356ec4acd1a343d1b6b939c96aba6cce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":770,
              "y":148},
            "size":{
              "width":26,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d119f15ac0e4cc2abe2a343ddf35b14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":770,
                  "y":148},
                "size":{
                  "width":26,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/ta人文章详情_ok/u27.png"}},
{
          "id":"dc46adacaec1483ab82fd91766884d04",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":816,
              "y":178},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49de596d4ec34ec1a3a5c6246ddf48ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":816,
                  "y":178},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b495cd79bf742a996f991fb4bc93f4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":816,
              "y":148},
            "size":{
              "width":26,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31422302d2084b779777fe047a08b5d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":816,
                  "y":148},
                "size":{
                  "width":26,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/ta人文章详情_ok/u27.png"}},
{
          "id":"b79819f215fa400a932a2aa4f253f14a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":799,
              "y":141},
            "size":{
              "width":10,
              "height":59},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/评论详情ok/u82_line.png"}},
{
          "id":"27658a6acf7347a2b13660c09fac921f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":499,
              "y":111},
            "size":{
              "width":681,
              "height":93}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e54713e3fa74f2283b304ab373804d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":499,
                  "y":111},
                "size":{
                  "width":681,
                  "height":93}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评论详情ok/u104.png"}}]}},
  "masters":{
    "7eae0193a65e431ca4eb8ac17758a1d2":{
      "packageId":"7eae0193a65e431ca4eb8ac17758a1d2",
      "type":"Axure:Master",
      "name":"基础版",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"af226c488fc941e99484bd2cec4340b8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":375,
                "height":667},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8dd1e2ae969848c89b84fa587a460694",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":375,
                    "height":667},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u1.png"}},
{
            "id":"7284e38442fc45348b8cd88281ff40b3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":375,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8616946ea493495780d9b0b3611246e1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":375,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u3.png"}},
{
            "id":"d36da1d223a64946a9e94711eff4d1fd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF6F6F6},
              "location":{
                "x":1,
                "y":623},
              "size":{
                "width":375,
                "height":44},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d16164721be54e25b197dd7f375e03e6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF6F6F6},
                  "location":{
                    "x":1,
                    "y":623},
                  "size":{
                    "width":375,
                    "height":44},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u5.png"}},
{
            "id":"315f60303f144000ae765c6d624bf077",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":29,
                "y":628},
              "size":{
                "width":22,
                "height":23},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b24b94422e9e4efb87aec6e5adef1e28",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":29,
                    "y":628},
                  "size":{
                    "width":22,
                    "height":23},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u7.png"}},
{
            "id":"31a4ebba4b024c0985313097bd4aa241",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "opacity":"0.5",
              "location":{
                "x":128,
                "y":628},
              "size":{
                "width":22,
                "height":21},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"acd0c3901d5d492eb40e111abba88684",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.5",
                  "location":{
                    "x":128,
                    "y":628},
                  "size":{
                    "width":22,
                    "height":21},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u9.png"}},
{
            "id":"edba010e20634dc1ac330c3bf8d76748",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "opacity":"0.5",
              "location":{
                "x":325,
                "y":628},
              "size":{
                "width":22,
                "height":22},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a16f9a63e6624c72ae69bd642a87de50",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.5",
                  "location":{
                    "x":325,
                    "y":628},
                  "size":{
                    "width":22,
                    "height":22},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u11.png"}},
{
            "id":"c7807a3a08ad4fed9a38119bc20c8755",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "opacity":"0.5",
              "location":{
                "x":226,
                "y":628},
              "size":{
                "width":22,
                "height":22},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c26cef48b2564499bc5c30f85331e754",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "opacity":"0.5",
                  "location":{
                    "x":226,
                    "y":628},
                  "size":{
                    "width":22,
                    "height":22},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/更新加载/u13.png"}},
{
            "id":"48809f0583444dcea10978992980261a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF868686,
                "opacity":1},
              "location":{
                "x":31,
                "y":652},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2378ba57c1274dd28ce75ae2102d4178",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF868686,
                    "opacity":1},
                  "location":{
                    "x":31,
                    "y":652},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5d3bac93c2934ccd9cdeaaf9db4428a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFBCBCBC,
                "opacity":1},
              "location":{
                "x":129,
                "y":652},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"314aac5cda1d4368ad98e59a8c422a75",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC,
                    "opacity":1},
                  "location":{
                    "x":129,
                    "y":652},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"262bd60e271747ee9a5adc99f7a3a2ef",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFBCBCBC,
                "opacity":1},
              "location":{
                "x":227,
                "y":652},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9a40c7bd14fe480ab352e3cea881e425",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC,
                    "opacity":1},
                  "location":{
                    "x":227,
                    "y":652},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"598eac4f5d6d41bba2fbab9208749178",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFBCBCBC,
                "opacity":1},
              "location":{
                "x":327,
                "y":652},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"99145e3a21ad4858a239c1698775eac9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC,
                    "opacity":1},
                  "location":{
                    "x":327,
                    "y":652},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "4b03b57a7a9f42dda127d245b648e6cd":{
      "scriptId":"u0",
      "af226c488fc941e99484bd2cec4340b8":{
        "scriptId":"u1"},
      "8dd1e2ae969848c89b84fa587a460694":{
        "scriptId":"u2"},
      "7284e38442fc45348b8cd88281ff40b3":{
        "scriptId":"u3"},
      "8616946ea493495780d9b0b3611246e1":{
        "scriptId":"u4"},
      "d36da1d223a64946a9e94711eff4d1fd":{
        "scriptId":"u5"},
      "d16164721be54e25b197dd7f375e03e6":{
        "scriptId":"u6"},
      "315f60303f144000ae765c6d624bf077":{
        "scriptId":"u7"},
      "b24b94422e9e4efb87aec6e5adef1e28":{
        "scriptId":"u8"},
      "31a4ebba4b024c0985313097bd4aa241":{
        "scriptId":"u9"},
      "acd0c3901d5d492eb40e111abba88684":{
        "scriptId":"u10"},
      "edba010e20634dc1ac330c3bf8d76748":{
        "scriptId":"u11"},
      "a16f9a63e6624c72ae69bd642a87de50":{
        "scriptId":"u12"},
      "c7807a3a08ad4fed9a38119bc20c8755":{
        "scriptId":"u13"},
      "c26cef48b2564499bc5c30f85331e754":{
        "scriptId":"u14"},
      "48809f0583444dcea10978992980261a":{
        "scriptId":"u15"},
      "2378ba57c1274dd28ce75ae2102d4178":{
        "scriptId":"u16"},
      "5d3bac93c2934ccd9cdeaaf9db4428a6":{
        "scriptId":"u17"},
      "314aac5cda1d4368ad98e59a8c422a75":{
        "scriptId":"u18"},
      "262bd60e271747ee9a5adc99f7a3a2ef":{
        "scriptId":"u19"},
      "9a40c7bd14fe480ab352e3cea881e425":{
        "scriptId":"u20"},
      "598eac4f5d6d41bba2fbab9208749178":{
        "scriptId":"u21"},
      "99145e3a21ad4858a239c1698775eac9":{
        "scriptId":"u22"}},
    "f005539e1928407592faa3ae055f470f":{
      "scriptId":"u23"},
    "1f85f86fbbb749ecbb48302d24ea8c9f":{
      "scriptId":"u24"},
    "5f8ef7e07f284ef290683779bc674bf1":{
      "scriptId":"u25"},
    "da6087a31dbc4a50af58452226d87a86":{
      "scriptId":"u26"},
    "4770b93d568443dc8322b5c7506686f6":{
      "scriptId":"u27"},
    "d08b807276974f83a320ced141947269":{
      "scriptId":"u28"},
    "ad6ec22f3d974503bba873d04966ccff":{
      "scriptId":"u29"},
    "5447f56dd9834d07aa13816ed90fecf6":{
      "scriptId":"u30"},
    "d3ebcb745b1f49d48469052798a7d391":{
      "scriptId":"u31"},
    "1361a0cadfdd43069b51b794ab55f5bb":{
      "scriptId":"u32"},
    "5b1a16b92d1b4531b2efccc75acb624e":{
      "scriptId":"u33"},
    "8fc3942174c8441ebec27858717e06fd":{
      "scriptId":"u34"},
    "6ae217ca2a6b4e28922a750a20ce6d38":{
      "scriptId":"u35"},
    "e609fb2825e04e9c94ea20102f29438f":{
      "scriptId":"u36"},
    "4f2ad39e24dd488b941f8b4cc839d3af":{
      "scriptId":"u37"},
    "226aefea9cd141d183fb72d8a611fb4c":{
      "scriptId":"u38"},
    "1c96d6d2bfc94f95a3102d1296bd2b91":{
      "scriptId":"u39"},
    "3438403bf87a49f69f8bfca94e8ef08c":{
      "scriptId":"u40"},
    "8143b4cffa584e1280d7a07a311d0174":{
      "scriptId":"u41"},
    "fd75d40e248d40da99c0e998bbe79fc2":{
      "scriptId":"u42"},
    "5b35e2a25307427e9cb023ba13d7d162":{
      "scriptId":"u43"},
    "e5d53c15b09c4f53ab0d2388a055215a":{
      "scriptId":"u44"},
    "6247a7ecb6924e9186dc70311c6d4824":{
      "scriptId":"u45"},
    "31cc37b176f04f82ac963e99490f82d6":{
      "scriptId":"u46"},
    "897baf60476d483386890c70bdbbe8ce":{
      "scriptId":"u47"},
    "4fa1457cdf964ae397bd40f992669048":{
      "scriptId":"u48"},
    "93bd56b59494432ebe328a454067a7b6":{
      "scriptId":"u49"},
    "557de1f6e4b04674b0cb67c565655694":{
      "scriptId":"u50"},
    "2f81365fb6744932a9d6f50fef491e56":{
      "scriptId":"u51"},
    "31b7b26774084a89a13fcc28b91cb511":{
      "scriptId":"u52"},
    "58c94dc28b844092ac7e5a2aeeea6833":{
      "scriptId":"u53"},
    "706e9f46bc6b453d8e7030c4caf27bb7":{
      "scriptId":"u54"},
    "ae0805d3cd0143c2a8d20f14fadfa11d":{
      "scriptId":"u55"},
    "79348dec5fb04dd494cdfd72d0811c1d":{
      "scriptId":"u56"},
    "db948b29d73e4d608c05f0d35ea2d212":{
      "scriptId":"u57"},
    "48ac85e3d38c44eba333e98fddea60fa":{
      "scriptId":"u58"},
    "229b5f6351db46d28bd60cc96e66c882":{
      "scriptId":"u59"},
    "4e8b95e5c68e4892b4bec7220d5204cd":{
      "scriptId":"u60"},
    "65b4a8d55420437788934f73bcfaf644":{
      "scriptId":"u61"},
    "8a8002fe6cb644c79a12cdfa3bfe17d8":{
      "scriptId":"u62"},
    "3aa65b47f5a64faaa9e17f3e8e451fde":{
      "scriptId":"u63"},
    "41b6251bf3d04f55af17ccd93bd7ed80":{
      "scriptId":"u64"},
    "6791a0ee21b24030a8ee41e073cc7a0a":{
      "scriptId":"u65"},
    "914c58222f124d46b4bf5e67ac5e1838":{
      "scriptId":"u66"},
    "2fb6e178647d4e9ba390a5ef72f9729a":{
      "scriptId":"u67"},
    "5ba043a80394479196860b5d8bad7639":{
      "scriptId":"u68"},
    "6a1e9d79497448dd808c97e66302fa77":{
      "scriptId":"u69"},
    "be37bde4fc1644aca537244a5ececd96":{
      "scriptId":"u70"},
    "d33869c7e8d1460ca560d967402501ab":{
      "scriptId":"u71"},
    "b9a01abad50c44d08b4248838b4fe8ea":{
      "scriptId":"u72"},
    "9b7942e6b4b5446d8bfcef5d5daa7c0a":{
      "scriptId":"u73"},
    "11cb4394cfb34cd7a61a443dc4b8d8a2":{
      "scriptId":"u74"},
    "7437761a13ae4b848e034c5d8afb9930":{
      "scriptId":"u75"},
    "713a6bdea23740d0a430a53a3b6766fb":{
      "scriptId":"u76"},
    "853f8226f917411a8e0e1548b30f7363":{
      "scriptId":"u77"},
    "f6fe14d937854f4faece9fc7864a44d3":{
      "scriptId":"u78"},
    "a0712a8dc6dd4960afdc3eae755f6f96":{
      "scriptId":"u79"},
    "4119579a9650414db4e13a89a6ed4c90":{
      "scriptId":"u80"},
    "087428765d2d478f8a59fcdaba0d8816":{
      "scriptId":"u81"},
    "34cf9674bcc64440b139c968c4c6ccf4":{
      "scriptId":"u82"},
    "aeccd8aca7e84eec82470216cb1c182f":{
      "scriptId":"u83"},
    "511ce5420c634b8da4bd9c4162dd60f0":{
      "scriptId":"u84"},
    "5b0d842ed8f1429abc85680ef283a0ce":{
      "scriptId":"u85"},
    "ca9ec6b54be342b9b4de3293290d824e":{
      "scriptId":"u86"},
    "d50de8a9b2ef406b88c5f809cd963377":{
      "scriptId":"u87"},
    "4ab4c9fca1744211a111bcd0cff8549b":{
      "scriptId":"u88"},
    "e5458bb72ffc42fea15f1dd880c31b98":{
      "scriptId":"u89"},
    "abd487c69a044af7a239993ee971a837":{
      "scriptId":"u90"},
    "22db26de4ee5458fb57f19cf30396f12":{
      "scriptId":"u91"},
    "c80bb6b72a464d648ddd64cd87a90de5":{
      "scriptId":"u92"},
    "6500b2737d844620aba2960444c9527a":{
      "scriptId":"u93"},
    "64b167fa7baa44aa833457a88dc3ee78":{
      "scriptId":"u94"},
    "cd69bee435e14b02a9017b57236fbc4b":{
      "scriptId":"u95"},
    "4425e5d73635429a900499702abc94b6":{
      "scriptId":"u96"},
    "356ec4acd1a343d1b6b939c96aba6cce":{
      "scriptId":"u97"},
    "5d119f15ac0e4cc2abe2a343ddf35b14":{
      "scriptId":"u98"},
    "dc46adacaec1483ab82fd91766884d04":{
      "scriptId":"u99"},
    "49de596d4ec34ec1a3a5c6246ddf48ae":{
      "scriptId":"u100"},
    "4b495cd79bf742a996f991fb4bc93f4e":{
      "scriptId":"u101"},
    "31422302d2084b779777fe047a08b5d4":{
      "scriptId":"u102"},
    "b79819f215fa400a932a2aa4f253f14a":{
      "scriptId":"u103"},
    "27658a6acf7347a2b13660c09fac921f":{
      "scriptId":"u104"},
    "7e54713e3fa74f2283b304ab373804d0":{
      "scriptId":"u105"}}});